// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/lifecycle/lifecycle.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/lifecycle/lifecycle.go -destination=internal/app/lifecycle/lifecycle_mock.go -package=lifecycle
//

// Package lifecycle is a generated GoMock package.
package lifecycle

import (
	process "fuku/internal/app/process"
	exec "os/exec"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockLifecycle is a mock of Lifecycle interface.
type MockLifecycle struct {
	ctrl     *gomock.Controller
	recorder *MockLifecycleMockRecorder
	isgomock struct{}
}

// MockLifecycleMockRecorder is the mock recorder for MockLifecycle.
type MockLifecycleMockRecorder struct {
	mock *MockLifecycle
}

// NewMockLifecycle creates a new mock instance.
func NewMockLifecycle(ctrl *gomock.Controller) *MockLifecycle {
	mock := &MockLifecycle{ctrl: ctrl}
	mock.recorder = &MockLifecycleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLifecycle) EXPECT() *MockLifecycleMockRecorder {
	return m.recorder
}

// Configure mocks base method.
func (m *MockLifecycle) Configure(cmd *exec.Cmd) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Configure", cmd)
}

// Configure indicates an expected call of Configure.
func (mr *MockLifecycleMockRecorder) Configure(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configure", reflect.TypeOf((*MockLifecycle)(nil).Configure), cmd)
}

// Terminate mocks base method.
func (m *MockLifecycle) Terminate(proc process.Process, timeout time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Terminate", proc, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Terminate indicates an expected call of Terminate.
func (mr *MockLifecycleMockRecorder) Terminate(proc, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Terminate", reflect.TypeOf((*MockLifecycle)(nil).Terminate), proc, timeout)
}
