version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - forbidigo
    - gochecknoinits
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wsl_v5
  settings:
    forbidigo:
      forbid:
        - pattern: ^time\.Sleep$
          msg: "time.Sleep in tests is a code smell. Use channel-based synchronization instead."
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gosec
        path: _test\.go
      - linters:
          - forbidigo
        path-except: _test\.go
    paths:
      - docs
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
