// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/preflight/preflight.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/preflight/preflight.go -destination=internal/app/preflight/preflight_mock.go -package=preflight
//

// Package preflight is a generated GoMock package.
package preflight

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPreflight is a mock of Preflight interface.
type MockPreflight struct {
	ctrl     *gomock.Controller
	recorder *MockPreflightMockRecorder
	isgomock struct{}
}

// MockPreflightMockRecorder is the mock recorder for MockPreflight.
type MockPreflightMockRecorder struct {
	mock *MockPreflight
}

// NewMockPreflight creates a new mock instance.
func NewMockPreflight(ctrl *gomock.Controller) *MockPreflight {
	mock := &MockPreflight{ctrl: ctrl}
	mock.recorder = &MockPreflightMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreflight) EXPECT() *MockPreflightMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockPreflight) Cleanup(ctx context.Context, dirs map[string]string) ([]Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", ctx, dirs)
	ret0, _ := ret[0].([]Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockPreflightMockRecorder) Cleanup(ctx, dirs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockPreflight)(nil).Cleanup), ctx, dirs)
}
