// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/ui/filter.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/ui/filter.go -destination=internal/app/ui/filter_mock.go -package=ui
//

// Package ui is a generated GoMock package.
package ui

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogFilter is a mock of LogFilter interface.
type MockLogFilter struct {
	ctrl     *gomock.Controller
	recorder *MockLogFilterMockRecorder
	isgomock struct{}
}

// MockLogFilterMockRecorder is the mock recorder for MockLogFilter.
type MockLogFilterMockRecorder struct {
	mock *MockLogFilter
}

// NewMockLogFilter creates a new mock instance.
func NewMockLogFilter(ctrl *gomock.Controller) *MockLogFilter {
	mock := &MockLogFilter{ctrl: ctrl}
	mock.recorder = &MockLogFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogFilter) EXPECT() *MockLogFilterMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockLogFilter) All() map[string]bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All")
	ret0, _ := ret[0].(map[string]bool)
	return ret0
}

// All indicates an expected call of All.
func (mr *MockLogFilterMockRecorder) All() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockLogFilter)(nil).All))
}

// IsEnabled mocks base method.
func (m *MockLogFilter) IsEnabled(service string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled", service)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockLogFilterMockRecorder) IsEnabled(service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockLogFilter)(nil).IsEnabled), service)
}

// Set mocks base method.
func (m *MockLogFilter) Set(service string, enabled bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", service, enabled)
}

// Set indicates an expected call of Set.
func (mr *MockLogFilterMockRecorder) Set(service, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockLogFilter)(nil).Set), service, enabled)
}

// ToggleAll mocks base method.
func (m *MockLogFilter) ToggleAll(services []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ToggleAll", services)
}

// ToggleAll indicates an expected call of ToggleAll.
func (mr *MockLogFilterMockRecorder) ToggleAll(services any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleAll", reflect.TypeOf((*MockLogFilter)(nil).ToggleAll), services)
}
