// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/ui/logview.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/ui/logview.go -destination=internal/app/ui/logview_mock.go -package=ui
//

// Package ui is a generated GoMock package.
package ui

import (
	reflect "reflect"

	tea "github.com/charmbracelet/bubbletea"
	gomock "go.uber.org/mock/gomock"
)

// MockLogView is a mock of LogView interface.
type MockLogView struct {
	ctrl     *gomock.Controller
	recorder *MockLogViewMockRecorder
	isgomock struct{}
}

// MockLogViewMockRecorder is the mock recorder for MockLogView.
type MockLogViewMockRecorder struct {
	mock *MockLogView
}

// NewMockLogView creates a new mock instance.
func NewMockLogView(ctrl *gomock.Controller) *MockLogView {
	mock := &MockLogView{ctrl: ctrl}
	mock.recorder = &MockLogViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogView) EXPECT() *MockLogViewMockRecorder {
	return m.recorder
}

// Autoscroll mocks base method.
func (m *MockLogView) Autoscroll() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Autoscroll")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Autoscroll indicates an expected call of Autoscroll.
func (mr *MockLogViewMockRecorder) Autoscroll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Autoscroll", reflect.TypeOf((*MockLogView)(nil).Autoscroll))
}

// Clear mocks base method.
func (m *MockLogView) Clear() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear.
func (mr *MockLogViewMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockLogView)(nil).Clear))
}

// HandleKey mocks base method.
func (m *MockLogView) HandleKey(msg tea.KeyMsg) tea.Cmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleKey", msg)
	ret0, _ := ret[0].(tea.Cmd)
	return ret0
}

// HandleKey indicates an expected call of HandleKey.
func (mr *MockLogViewMockRecorder) HandleKey(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleKey", reflect.TypeOf((*MockLogView)(nil).HandleKey), msg)
}

// HandleLog mocks base method.
func (m *MockLogView) HandleLog(entry LogEntry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleLog", entry)
}

// HandleLog indicates an expected call of HandleLog.
func (mr *MockLogViewMockRecorder) HandleLog(entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLog", reflect.TypeOf((*MockLogView)(nil).HandleLog), entry)
}

// IsEnabled mocks base method.
func (m *MockLogView) IsEnabled(service string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled", service)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockLogViewMockRecorder) IsEnabled(service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockLogView)(nil).IsEnabled), service)
}

// SetEnabled mocks base method.
func (m *MockLogView) SetEnabled(service string, enabled bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEnabled", service, enabled)
}

// SetEnabled indicates an expected call of SetEnabled.
func (mr *MockLogViewMockRecorder) SetEnabled(service, enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnabled", reflect.TypeOf((*MockLogView)(nil).SetEnabled), service, enabled)
}

// SetSize mocks base method.
func (m *MockLogView) SetSize(width, height int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSize", width, height)
}

// SetSize indicates an expected call of SetSize.
func (mr *MockLogViewMockRecorder) SetSize(width, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSize", reflect.TypeOf((*MockLogView)(nil).SetSize), width, height)
}

// ToggleAll mocks base method.
func (m *MockLogView) ToggleAll(services []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ToggleAll", services)
}

// ToggleAll indicates an expected call of ToggleAll.
func (mr *MockLogViewMockRecorder) ToggleAll(services any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleAll", reflect.TypeOf((*MockLogView)(nil).ToggleAll), services)
}

// ToggleAutoscroll mocks base method.
func (m *MockLogView) ToggleAutoscroll() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ToggleAutoscroll")
}

// ToggleAutoscroll indicates an expected call of ToggleAutoscroll.
func (mr *MockLogViewMockRecorder) ToggleAutoscroll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleAutoscroll", reflect.TypeOf((*MockLogView)(nil).ToggleAutoscroll))
}

// View mocks base method.
func (m *MockLogView) View() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "View")
	ret0, _ := ret[0].(string)
	return ret0
}

// View indicates an expected call of View.
func (mr *MockLogViewMockRecorder) View() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "View", reflect.TypeOf((*MockLogView)(nil).View))
}
