// Code generated by MockGen. DO NOT EDIT.
// Source: ui.go
//
// Generated by this command:
//
//	mockgen -source=ui.go -destination=ui_mock.go -package=ui
//

// Package ui is a generated GoMock package.
package ui

import (
	tracker "fuku/internal/app/tracker"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProgress is a mock of Progress interface.
type MockProgress struct {
	ctrl     *gomock.Controller
	recorder *MockProgressMockRecorder
	isgomock struct{}
}

// MockProgressMockRecorder is the mock recorder for MockProgress.
type MockProgressMockRecorder struct {
	mock *MockProgress
}

// NewMockProgress creates a new mock instance.
func NewMockProgress(ctrl *gomock.Controller) *MockProgress {
	mock := &MockProgress{ctrl: ctrl}
	mock.recorder = &MockProgressMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgress) EXPECT() *MockProgressMockRecorder {
	return m.recorder
}

// IsReady mocks base method.
func (m *MockProgress) IsReady() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReady")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReady indicates an expected call of IsReady.
func (mr *MockProgressMockRecorder) IsReady() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReady", reflect.TypeOf((*MockProgress)(nil).IsReady))
}

// SetProgress mocks base method.
func (m *MockProgress) SetProgress(currentLayer, totalLayers int, step string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetProgress", currentLayer, totalLayers, step)
}

// SetProgress indicates an expected call of SetProgress.
func (mr *MockProgressMockRecorder) SetProgress(currentLayer, totalLayers, step any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProgress", reflect.TypeOf((*MockProgress)(nil).SetProgress), currentLayer, totalLayers, step)
}

// ShowLayer mocks base method.
func (m *MockProgress) ShowLayer(layerNum int, layerServices []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowLayer", layerNum, layerServices)
}

// ShowLayer indicates an expected call of ShowLayer.
func (mr *MockProgressMockRecorder) ShowLayer(layerNum, layerServices any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowLayer", reflect.TypeOf((*MockProgress)(nil).ShowLayer), layerNum, layerServices)
}

// ShowSummary mocks base method.
func (m *MockProgress) ShowSummary() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowSummary")
}

// ShowSummary indicates an expected call of ShowSummary.
func (mr *MockProgressMockRecorder) ShowSummary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowSummary", reflect.TypeOf((*MockProgress)(nil).ShowSummary))
}

// UpdateLayer mocks base method.
func (m *MockProgress) UpdateLayer(layerNum int, layerServices []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateLayer", layerNum, layerServices)
}

// UpdateLayer indicates an expected call of UpdateLayer.
func (mr *MockProgressMockRecorder) UpdateLayer(layerNum, layerServices any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLayer", reflect.TypeOf((*MockProgress)(nil).UpdateLayer), layerNum, layerServices)
}

// MockMode is a mock of Mode interface.
type MockMode struct {
	ctrl     *gomock.Controller
	recorder *MockModeMockRecorder
	isgomock struct{}
}

// MockModeMockRecorder is the mock recorder for MockMode.
type MockModeMockRecorder struct {
	mock *MockMode
}

// NewMockMode creates a new mock instance.
func NewMockMode(ctrl *gomock.Controller) *MockMode {
	mock := &MockMode{ctrl: ctrl}
	mock.recorder = &MockModeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMode) EXPECT() *MockModeMockRecorder {
	return m.recorder
}

// BufferLog mocks base method.
func (m *MockMode) BufferLog(line string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BufferLog", line)
}

// BufferLog indicates an expected call of BufferLog.
func (mr *MockModeMockRecorder) BufferLog(line any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BufferLog", reflect.TypeOf((*MockMode)(nil).BufferLog), line)
}

// IsBootstrap mocks base method.
func (m *MockMode) IsBootstrap() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBootstrap")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBootstrap indicates an expected call of IsBootstrap.
func (mr *MockModeMockRecorder) IsBootstrap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBootstrap", reflect.TypeOf((*MockMode)(nil).IsBootstrap))
}

// Phase mocks base method.
func (m *MockMode) Phase(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Phase", name)
}

// Phase indicates an expected call of Phase.
func (mr *MockModeMockRecorder) Phase(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Phase", reflect.TypeOf((*MockMode)(nil).Phase), name)
}

// SwitchToLogs mocks base method.
func (m *MockMode) SwitchToLogs() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SwitchToLogs")
}

// SwitchToLogs indicates an expected call of SwitchToLogs.
func (mr *MockModeMockRecorder) SwitchToLogs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchToLogs", reflect.TypeOf((*MockMode)(nil).SwitchToLogs))
}

// MockOutput is a mock of Output interface.
type MockOutput struct {
	ctrl     *gomock.Controller
	recorder *MockOutputMockRecorder
	isgomock struct{}
}

// MockOutputMockRecorder is the mock recorder for MockOutput.
type MockOutputMockRecorder struct {
	mock *MockOutput
}

// NewMockOutput creates a new mock instance.
func NewMockOutput(ctrl *gomock.Controller) *MockOutput {
	mock := &MockOutput{ctrl: ctrl}
	mock.recorder = &MockOutputMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutput) EXPECT() *MockOutputMockRecorder {
	return m.recorder
}

// ProgressBar mocks base method.
func (m *MockOutput) ProgressBar(current, total, width int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProgressBar", current, total, width)
	ret0, _ := ret[0].(string)
	return ret0
}

// ProgressBar indicates an expected call of ProgressBar.
func (mr *MockOutputMockRecorder) ProgressBar(current, total, width any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProgressBar", reflect.TypeOf((*MockOutput)(nil).ProgressBar), current, total, width)
}

// ShowError mocks base method.
func (m *MockOutput) ShowError(serviceName string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowError", serviceName, err)
}

// ShowError indicates an expected call of ShowError.
func (mr *MockOutputMockRecorder) ShowError(serviceName, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowError", reflect.TypeOf((*MockOutput)(nil).ShowError), serviceName, err)
}

// ShowSuccess mocks base method.
func (m *MockOutput) ShowSuccess() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowSuccess")
}

// ShowSuccess indicates an expected call of ShowSuccess.
func (mr *MockOutputMockRecorder) ShowSuccess() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowSuccess", reflect.TypeOf((*MockOutput)(nil).ShowSuccess))
}

// MockDisplay is a mock of Display interface.
type MockDisplay struct {
	ctrl     *gomock.Controller
	recorder *MockDisplayMockRecorder
	isgomock struct{}
}

// MockDisplayMockRecorder is the mock recorder for MockDisplay.
type MockDisplayMockRecorder struct {
	mock *MockDisplay
}

// NewMockDisplay creates a new mock instance.
func NewMockDisplay(ctrl *gomock.Controller) *MockDisplay {
	mock := &MockDisplay{ctrl: ctrl}
	mock.recorder = &MockDisplayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDisplay) EXPECT() *MockDisplayMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockDisplay) Add(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", name)
}

// Add indicates an expected call of Add.
func (mr *MockDisplayMockRecorder) Add(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockDisplay)(nil).Add), name)
}

// BufferLog mocks base method.
func (m *MockDisplay) BufferLog(line string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BufferLog", line)
}

// BufferLog indicates an expected call of BufferLog.
func (mr *MockDisplayMockRecorder) BufferLog(line any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BufferLog", reflect.TypeOf((*MockDisplay)(nil).BufferLog), line)
}

// Error mocks base method.
func (m *MockDisplay) Error(name string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", name, err)
}

// Error indicates an expected call of Error.
func (mr *MockDisplayMockRecorder) Error(name, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockDisplay)(nil).Error), name, err)
}

// GetAnalytics mocks base method.
func (m *MockDisplay) GetAnalytics() *Analytics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalytics")
	ret0, _ := ret[0].(*Analytics)
	return ret0
}

// GetAnalytics indicates an expected call of GetAnalytics.
func (mr *MockDisplayMockRecorder) GetAnalytics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalytics", reflect.TypeOf((*MockDisplay)(nil).GetAnalytics))
}

// GetCurrentLayer mocks base method.
func (m *MockDisplay) GetCurrentLayer() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentLayer")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetCurrentLayer indicates an expected call of GetCurrentLayer.
func (mr *MockDisplayMockRecorder) GetCurrentLayer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentLayer", reflect.TypeOf((*MockDisplay)(nil).GetCurrentLayer))
}

// GetCurrentStep mocks base method.
func (m *MockDisplay) GetCurrentStep() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentStep")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCurrentStep indicates an expected call of GetCurrentStep.
func (mr *MockDisplayMockRecorder) GetCurrentStep() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentStep", reflect.TypeOf((*MockDisplay)(nil).GetCurrentStep))
}

// GetServicesStarted mocks base method.
func (m *MockDisplay) GetServicesStarted() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServicesStarted")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetServicesStarted indicates an expected call of GetServicesStarted.
func (mr *MockDisplayMockRecorder) GetServicesStarted() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServicesStarted", reflect.TypeOf((*MockDisplay)(nil).GetServicesStarted))
}

// GetTotalLayers mocks base method.
func (m *MockDisplay) GetTotalLayers() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalLayers")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetTotalLayers indicates an expected call of GetTotalLayers.
func (mr *MockDisplayMockRecorder) GetTotalLayers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalLayers", reflect.TypeOf((*MockDisplay)(nil).GetTotalLayers))
}

// GetTotalServices mocks base method.
func (m *MockDisplay) GetTotalServices() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalServices")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetTotalServices indicates an expected call of GetTotalServices.
func (mr *MockDisplayMockRecorder) GetTotalServices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalServices", reflect.TypeOf((*MockDisplay)(nil).GetTotalServices))
}

// IsBootstrap mocks base method.
func (m *MockDisplay) IsBootstrap() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBootstrap")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBootstrap indicates an expected call of IsBootstrap.
func (mr *MockDisplayMockRecorder) IsBootstrap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBootstrap", reflect.TypeOf((*MockDisplay)(nil).IsBootstrap))
}

// IsReady mocks base method.
func (m *MockDisplay) IsReady() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReady")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReady indicates an expected call of IsReady.
func (mr *MockDisplayMockRecorder) IsReady() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReady", reflect.TypeOf((*MockDisplay)(nil).IsReady))
}

// Phase mocks base method.
func (m *MockDisplay) Phase(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Phase", name)
}

// Phase indicates an expected call of Phase.
func (mr *MockDisplayMockRecorder) Phase(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Phase", reflect.TypeOf((*MockDisplay)(nil).Phase), name)
}

// ProgressBar mocks base method.
func (m *MockDisplay) ProgressBar(current, total, width int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProgressBar", current, total, width)
	ret0, _ := ret[0].(string)
	return ret0
}

// ProgressBar indicates an expected call of ProgressBar.
func (mr *MockDisplayMockRecorder) ProgressBar(current, total, width any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProgressBar", reflect.TypeOf((*MockDisplay)(nil).ProgressBar), current, total, width)
}

// SetProgress mocks base method.
func (m *MockDisplay) SetProgress(currentLayer, totalLayers int, step string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetProgress", currentLayer, totalLayers, step)
}

// SetProgress indicates an expected call of SetProgress.
func (mr *MockDisplayMockRecorder) SetProgress(currentLayer, totalLayers, step any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProgress", reflect.TypeOf((*MockDisplay)(nil).SetProgress), currentLayer, totalLayers, step)
}

// ShowError mocks base method.
func (m *MockDisplay) ShowError(serviceName string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowError", serviceName, err)
}

// ShowError indicates an expected call of ShowError.
func (mr *MockDisplayMockRecorder) ShowError(serviceName, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowError", reflect.TypeOf((*MockDisplay)(nil).ShowError), serviceName, err)
}

// ShowLayer mocks base method.
func (m *MockDisplay) ShowLayer(layerNum int, layerServices []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowLayer", layerNum, layerServices)
}

// ShowLayer indicates an expected call of ShowLayer.
func (mr *MockDisplayMockRecorder) ShowLayer(layerNum, layerServices any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowLayer", reflect.TypeOf((*MockDisplay)(nil).ShowLayer), layerNum, layerServices)
}

// ShowSuccess mocks base method.
func (m *MockDisplay) ShowSuccess() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowSuccess")
}

// ShowSuccess indicates an expected call of ShowSuccess.
func (mr *MockDisplayMockRecorder) ShowSuccess() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowSuccess", reflect.TypeOf((*MockDisplay)(nil).ShowSuccess))
}

// ShowSummary mocks base method.
func (m *MockDisplay) ShowSummary() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowSummary")
}

// ShowSummary indicates an expected call of ShowSummary.
func (mr *MockDisplayMockRecorder) ShowSummary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowSummary", reflect.TypeOf((*MockDisplay)(nil).ShowSummary))
}

// SwitchToLogs mocks base method.
func (m *MockDisplay) SwitchToLogs() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SwitchToLogs")
}

// SwitchToLogs indicates an expected call of SwitchToLogs.
func (mr *MockDisplayMockRecorder) SwitchToLogs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchToLogs", reflect.TypeOf((*MockDisplay)(nil).SwitchToLogs))
}

// Update mocks base method.
func (m *MockDisplay) Update(name string, status tracker.Status) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", name, status)
}

// Update indicates an expected call of Update.
func (mr *MockDisplayMockRecorder) Update(name, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDisplay)(nil).Update), name, status)
}

// UpdateLayer mocks base method.
func (m *MockDisplay) UpdateLayer(layerNum int, layerServices []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateLayer", layerNum, layerServices)
}

// UpdateLayer indicates an expected call of UpdateLayer.
func (mr *MockDisplayMockRecorder) UpdateLayer(layerNum, layerServices any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLayer", reflect.TypeOf((*MockDisplay)(nil).UpdateLayer), layerNum, layerServices)
}
