// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/process/process.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/process/process.go -destination=internal/app/process/process_mock.go -package=process
//

// Package process is a generated GoMock package.
package process

import (
	io "io"
	exec "os/exec"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProcess is a mock of Process interface.
type MockProcess struct {
	ctrl     *gomock.Controller
	recorder *MockProcessMockRecorder
	isgomock struct{}
}

// MockProcessMockRecorder is the mock recorder for MockProcess.
type MockProcessMockRecorder struct {
	mock *MockProcess
}

// NewMockProcess creates a new mock instance.
func NewMockProcess(ctrl *gomock.Controller) *MockProcess {
	mock := &MockProcess{ctrl: ctrl}
	mock.recorder = &MockProcessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcess) EXPECT() *MockProcessMockRecorder {
	return m.recorder
}

// Cmd mocks base method.
func (m *MockProcess) Cmd() *exec.Cmd {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cmd")
	ret0, _ := ret[0].(*exec.Cmd)
	return ret0
}

// Cmd indicates an expected call of Cmd.
func (mr *MockProcessMockRecorder) Cmd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cmd", reflect.TypeOf((*MockProcess)(nil).Cmd))
}

// Done mocks base method.
func (m *MockProcess) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockProcessMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockProcess)(nil).Done))
}

// Name mocks base method.
func (m *MockProcess) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockProcessMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockProcess)(nil).Name))
}

// Ready mocks base method.
func (m *MockProcess) Ready() <-chan error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ready")
	ret0, _ := ret[0].(<-chan error)
	return ret0
}

// Ready indicates an expected call of Ready.
func (mr *MockProcessMockRecorder) Ready() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ready", reflect.TypeOf((*MockProcess)(nil).Ready))
}

// SignalReady mocks base method.
func (m *MockProcess) SignalReady(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SignalReady", err)
}

// SignalReady indicates an expected call of SignalReady.
func (mr *MockProcessMockRecorder) SignalReady(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalReady", reflect.TypeOf((*MockProcess)(nil).SignalReady), err)
}

// StderrReader mocks base method.
func (m *MockProcess) StderrReader() *io.PipeReader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StderrReader")
	ret0, _ := ret[0].(*io.PipeReader)
	return ret0
}

// StderrReader indicates an expected call of StderrReader.
func (mr *MockProcessMockRecorder) StderrReader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StderrReader", reflect.TypeOf((*MockProcess)(nil).StderrReader))
}

// StdoutReader mocks base method.
func (m *MockProcess) StdoutReader() *io.PipeReader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StdoutReader")
	ret0, _ := ret[0].(*io.PipeReader)
	return ret0
}

// StdoutReader indicates an expected call of StdoutReader.
func (mr *MockProcessMockRecorder) StdoutReader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StdoutReader", reflect.TypeOf((*MockProcess)(nil).StdoutReader))
}
