// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/ui/navigation/navigator.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/ui/navigation/navigator.go -destination=internal/app/ui/navigation/navigator_mock.go -package=navigation
//

// Package navigation is a generated GoMock package.
package navigation

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNavigator is a mock of Navigator interface.
type MockNavigator struct {
	ctrl     *gomock.Controller
	recorder *MockNavigatorMockRecorder
	isgomock struct{}
}

// MockNavigatorMockRecorder is the mock recorder for MockNavigator.
type MockNavigatorMockRecorder struct {
	mock *MockNavigator
}

// NewMockNavigator creates a new mock instance.
func NewMockNavigator(ctrl *gomock.Controller) *MockNavigator {
	mock := &MockNavigator{ctrl: ctrl}
	mock.recorder = &MockNavigatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNavigator) EXPECT() *MockNavigatorMockRecorder {
	return m.recorder
}

// CurrentView mocks base method.
func (m *MockNavigator) CurrentView() View {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentView")
	ret0, _ := ret[0].(View)
	return ret0
}

// CurrentView indicates an expected call of CurrentView.
func (mr *MockNavigatorMockRecorder) CurrentView() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentView", reflect.TypeOf((*MockNavigator)(nil).CurrentView))
}

// IsLogs mocks base method.
func (m *MockNavigator) IsLogs() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLogs")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLogs indicates an expected call of IsLogs.
func (mr *MockNavigatorMockRecorder) IsLogs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLogs", reflect.TypeOf((*MockNavigator)(nil).IsLogs))
}

// IsServices mocks base method.
func (m *MockNavigator) IsServices() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsServices")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsServices indicates an expected call of IsServices.
func (mr *MockNavigatorMockRecorder) IsServices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsServices", reflect.TypeOf((*MockNavigator)(nil).IsServices))
}

// SwitchTo mocks base method.
func (m *MockNavigator) SwitchTo(view View) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SwitchTo", view)
}

// SwitchTo indicates an expected call of SwitchTo.
func (mr *MockNavigatorMockRecorder) SwitchTo(view any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchTo", reflect.TypeOf((*MockNavigator)(nil).SwitchTo), view)
}

// Toggle mocks base method.
func (m *MockNavigator) Toggle() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Toggle")
}

// Toggle indicates an expected call of Toggle.
func (mr *MockNavigatorMockRecorder) Toggle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Toggle", reflect.TypeOf((*MockNavigator)(nil).Toggle))
}
