// Code generated by MockGen. DO NOT EDIT.
// Source: internal/config/sentry/sentry.go
//
// Generated by this command:
//
//	mockgen -source=internal/config/sentry/sentry.go -destination=internal/config/sentry/sentry_mock.go -package=sentry
//

// Package sentry is a generated GoMock package.
package sentry

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSentry is a mock of Sentry interface.
type MockSentry struct {
	ctrl     *gomock.Controller
	recorder *MockSentryMockRecorder
	isgomock struct{}
}

// MockSentryMockRecorder is the mock recorder for MockSentry.
type MockSentryMockRecorder struct {
	mock *MockSentry
}

// NewMockSentry creates a new mock instance.
func NewMockSentry(ctrl *gomock.Controller) *MockSentry {
	mock := &MockSentry{ctrl: ctrl}
	mock.recorder = &MockSentryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSentry) EXPECT() *MockSentryMockRecorder {
	return m.recorder
}

// Flush mocks base method.
func (m *MockSentry) Flush() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Flush")
}

// Flush indicates an expected call of Flush.
func (mr *MockSentryMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockSentry)(nil).Flush))
}
