// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/app/doctor (interfaces: Environment,Filesystem,Profiles,Runtime)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/doctor/runner_mock_test.go -package=doctor fuku/internal/app/doctor Environment,Filesystem,Profiles,Runtime
//

// Package doctor is a generated GoMock package.
package doctor

import (
	context "context"
	model "fuku/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEnvironment is a mock of Environment interface.
type MockEnvironment struct {
	ctrl     *gomock.Controller
	recorder *MockEnvironmentMockRecorder
	isgomock struct{}
}

// MockEnvironmentMockRecorder is the mock recorder for MockEnvironment.
type MockEnvironmentMockRecorder struct {
	mock *MockEnvironment
}

// NewMockEnvironment creates a new mock instance.
func NewMockEnvironment(ctrl *gomock.Controller) *MockEnvironment {
	mock := &MockEnvironment{ctrl: ctrl}
	mock.recorder = &MockEnvironmentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvironment) EXPECT() *MockEnvironmentMockRecorder {
	return m.recorder
}

// Executable mocks base method.
func (m *MockEnvironment) Executable() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Executable")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Executable indicates an expected call of Executable.
func (mr *MockEnvironmentMockRecorder) Executable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Executable", reflect.TypeOf((*MockEnvironment)(nil).Executable))
}

// Getenv mocks base method.
func (m *MockEnvironment) Getenv(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Getenv", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// Getenv indicates an expected call of Getenv.
func (mr *MockEnvironmentMockRecorder) Getenv(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Getenv", reflect.TypeOf((*MockEnvironment)(nil).Getenv), key)
}

// PathExecutable mocks base method.
func (m *MockEnvironment) PathExecutable() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathExecutable")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PathExecutable indicates an expected call of PathExecutable.
func (mr *MockEnvironmentMockRecorder) PathExecutable() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathExecutable", reflect.TypeOf((*MockEnvironment)(nil).PathExecutable))
}

// MockFilesystem is a mock of Filesystem interface.
type MockFilesystem struct {
	ctrl     *gomock.Controller
	recorder *MockFilesystemMockRecorder
	isgomock struct{}
}

// MockFilesystemMockRecorder is the mock recorder for MockFilesystem.
type MockFilesystemMockRecorder struct {
	mock *MockFilesystem
}

// NewMockFilesystem creates a new mock instance.
func NewMockFilesystem(ctrl *gomock.Controller) *MockFilesystem {
	mock := &MockFilesystem{ctrl: ctrl}
	mock.recorder = &MockFilesystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilesystem) EXPECT() *MockFilesystemMockRecorder {
	return m.recorder
}

// DirExists mocks base method.
func (m *MockFilesystem) DirExists(path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirExists", path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DirExists indicates an expected call of DirExists.
func (mr *MockFilesystemMockRecorder) DirExists(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirExists", reflect.TypeOf((*MockFilesystem)(nil).DirExists), path)
}

// FileExists mocks base method.
func (m *MockFilesystem) FileExists(path string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", path)
	ret0, _ := ret[0].(bool)
	return ret0
}

// FileExists indicates an expected call of FileExists.
func (mr *MockFilesystemMockRecorder) FileExists(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockFilesystem)(nil).FileExists), path)
}

// Getwd mocks base method.
func (m *MockFilesystem) Getwd() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Getwd")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Getwd indicates an expected call of Getwd.
func (mr *MockFilesystemMockRecorder) Getwd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Getwd", reflect.TypeOf((*MockFilesystem)(nil).Getwd))
}

// MockProfiles is a mock of Profiles interface.
type MockProfiles struct {
	ctrl     *gomock.Controller
	recorder *MockProfilesMockRecorder
	isgomock struct{}
}

// MockProfilesMockRecorder is the mock recorder for MockProfiles.
type MockProfilesMockRecorder struct {
	mock *MockProfiles
}

// NewMockProfiles creates a new mock instance.
func NewMockProfiles(ctrl *gomock.Controller) *MockProfiles {
	mock := &MockProfiles{ctrl: ctrl}
	mock.recorder = &MockProfilesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfiles) EXPECT() *MockProfilesMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockProfiles) Resolve(profile string) (model.Tiers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", profile)
	ret0, _ := ret[0].(model.Tiers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockProfilesMockRecorder) Resolve(profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockProfiles)(nil).Resolve), profile)
}

// MockRuntime is a mock of Runtime interface.
type MockRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeMockRecorder
	isgomock struct{}
}

// MockRuntimeMockRecorder is the mock recorder for MockRuntime.
type MockRuntimeMockRecorder struct {
	mock *MockRuntime
}

// NewMockRuntime creates a new mock instance.
func NewMockRuntime(ctrl *gomock.Controller) *MockRuntime {
	mock := &MockRuntime{ctrl: ctrl}
	mock.recorder = &MockRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime) EXPECT() *MockRuntimeMockRecorder {
	return m.recorder
}

// ProbePort mocks base method.
func (m *MockRuntime) ProbePort(ctx context.Context, readiness model.Readiness) model.Port {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProbePort", ctx, readiness)
	ret0, _ := ret[0].(model.Port)
	return ret0
}

// ProbePort indicates an expected call of ProbePort.
func (mr *MockRuntimeMockRecorder) ProbePort(ctx, readiness any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProbePort", reflect.TypeOf((*MockRuntime)(nil).ProbePort), ctx, readiness)
}

// Socket mocks base method.
func (m *MockRuntime) Socket(fingerprint string) model.Socket {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Socket", fingerprint)
	ret0, _ := ret[0].(model.Socket)
	return ret0
}

// Socket indicates an expected call of Socket.
func (mr *MockRuntimeMockRecorder) Socket(fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Socket", reflect.TypeOf((*MockRuntime)(nil).Socket), fingerprint)
}

// Sockets mocks base method.
func (m *MockRuntime) Sockets() model.SocketScan {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sockets")
	ret0, _ := ret[0].(model.SocketScan)
	return ret0
}

// Sockets indicates an expected call of Sockets.
func (mr *MockRuntimeMockRecorder) Sockets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sockets", reflect.TypeOf((*MockRuntime)(nil).Sockets))
}
