// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/adapters/tui (interfaces: View)
//
// Generated by this command:
//
//	mockgen -destination=internal/adapters/tui/bus_mock_test.go -package=tui fuku/internal/adapters/tui View
//

// Package tui is a generated GoMock package.
package tui

import (
	reflect "reflect"

	tea "charm.land/bubbletea/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockView is a mock of View interface.
type MockView struct {
	ctrl     *gomock.Controller
	recorder *MockViewMockRecorder
	isgomock struct{}
}

// MockViewMockRecorder is the mock recorder for MockView.
type MockViewMockRecorder struct {
	mock *MockView
}

// NewMockView creates a new mock instance.
func NewMockView(ctrl *gomock.Controller) *MockView {
	mock := &MockView{ctrl: ctrl}
	mock.recorder = &MockViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockView) EXPECT() *MockViewMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockView) Send(msg tea.Msg) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Send", msg)
}

// Send indicates an expected call of Send.
func (mr *MockViewMockRecorder) Send(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockView)(nil).Send), msg)
}
