// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/adapters/tui (interfaces: Control)
//
// Generated by this command:
//
//	mockgen -destination=internal/adapters/tui/commands_mock_test.go -package=tui fuku/internal/adapters/tui Control
//

// Package tui is a generated GoMock package.
package tui

import (
	services "fuku/internal/app/services"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockControl is a mock of Control interface.
type MockControl struct {
	ctrl     *gomock.Controller
	recorder *MockControlMockRecorder
	isgomock struct{}
}

// MockControlMockRecorder is the mock recorder for MockControl.
type MockControlMockRecorder struct {
	mock *MockControl
}

// NewMockControl creates a new mock instance.
func NewMockControl(ctrl *gomock.Controller) *MockControl {
	mock := &MockControl{ctrl: ctrl}
	mock.recorder = &MockControlMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControl) EXPECT() *MockControlMockRecorder {
	return m.recorder
}

// Restart mocks base method.
func (m *MockControl) Restart(id string) (services.Admission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restart", id)
	ret0, _ := ret[0].(services.Admission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restart indicates an expected call of Restart.
func (mr *MockControlMockRecorder) Restart(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockControl)(nil).Restart), id)
}

// Start mocks base method.
func (m *MockControl) Start(id string) (services.Admission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", id)
	ret0, _ := ret[0].(services.Admission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockControlMockRecorder) Start(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockControl)(nil).Start), id)
}

// Stop mocks base method.
func (m *MockControl) Stop(id string) (services.Admission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", id)
	ret0, _ := ret[0].(services.Admission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stop indicates an expected call of Stop.
func (mr *MockControlMockRecorder) Stop(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockControl)(nil).Stop), id)
}

// StopAll mocks base method.
func (m *MockControl) StopAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// StopAll indicates an expected call of StopAll.
func (mr *MockControlMockRecorder) StopAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopAll", reflect.TypeOf((*MockControl)(nil).StopAll))
}
