// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/adapters/tui (interfaces: Output)
//
// Generated by this command:
//
//	mockgen -destination=internal/adapters/tui/program_mock_test.go -package=tui fuku/internal/adapters/tui Output
//

// Package tui is a generated GoMock package.
package tui

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOutput is a mock of Output interface.
type MockOutput struct {
	ctrl     *gomock.Controller
	recorder *MockOutputMockRecorder
	isgomock struct{}
}

// MockOutputMockRecorder is the mock recorder for MockOutput.
type MockOutputMockRecorder struct {
	mock *MockOutput
}

// NewMockOutput creates a new mock instance.
func NewMockOutput(ctrl *gomock.Controller) *MockOutput {
	mock := &MockOutput{ctrl: ctrl}
	mock.recorder = &MockOutputMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutput) EXPECT() *MockOutputMockRecorder {
	return m.recorder
}

// SetEnabled mocks base method.
func (m *MockOutput) SetEnabled(enabled bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEnabled", enabled)
}

// SetEnabled indicates an expected call of SetEnabled.
func (mr *MockOutputMockRecorder) SetEnabled(enabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEnabled", reflect.TypeOf((*MockOutput)(nil).SetEnabled), enabled)
}
