// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/app/updater (interfaces: ReleaseSource)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/updater/check_mock_test.go -package=updater fuku/internal/app/updater ReleaseSource
//

// Package updater is a generated GoMock package.
package updater

import (
	context "context"
	model "fuku/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReleaseSource is a mock of ReleaseSource interface.
type MockReleaseSource struct {
	ctrl     *gomock.Controller
	recorder *MockReleaseSourceMockRecorder
	isgomock struct{}
}

// MockReleaseSourceMockRecorder is the mock recorder for MockReleaseSource.
type MockReleaseSourceMockRecorder struct {
	mock *MockReleaseSource
}

// NewMockReleaseSource creates a new mock instance.
func NewMockReleaseSource(ctrl *gomock.Controller) *MockReleaseSource {
	mock := &MockReleaseSource{ctrl: ctrl}
	mock.recorder = &MockReleaseSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReleaseSource) EXPECT() *MockReleaseSourceMockRecorder {
	return m.recorder
}

// Latest mocks base method.
func (m *MockReleaseSource) Latest(ctx context.Context) (model.Release, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Latest", ctx)
	ret0, _ := ret[0].(model.Release)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Latest indicates an expected call of Latest.
func (mr *MockReleaseSourceMockRecorder) Latest(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Latest", reflect.TypeOf((*MockReleaseSource)(nil).Latest), ctx)
}
