// Code generated by MockGen. DO NOT EDIT.
// Source: state.go
//
// Generated by this command:
//
//	mockgen -source=state.go -destination=state_mock.go -package=state
//

// Package state is a generated GoMock package.
package state

import (
	runner "fuku/internal/app/runner"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// AddService mocks base method.
func (m *MockManager) AddService(svc *ServiceStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddService", svc)
}

// AddService indicates an expected call of AddService.
func (mr *MockManagerMockRecorder) AddService(svc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddService", reflect.TypeOf((*MockManager)(nil).AddService), svc)
}

// GetPhase mocks base method.
func (m *MockManager) GetPhase() runner.Phase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPhase")
	ret0, _ := ret[0].(runner.Phase)
	return ret0
}

// GetPhase indicates an expected call of GetPhase.
func (mr *MockManagerMockRecorder) GetPhase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPhase", reflect.TypeOf((*MockManager)(nil).GetPhase))
}

// GetService mocks base method.
func (m *MockManager) GetService(name string) (*ServiceStatus, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetService", name)
	ret0, _ := ret[0].(*ServiceStatus)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetService indicates an expected call of GetService.
func (mr *MockManagerMockRecorder) GetService(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetService", reflect.TypeOf((*MockManager)(nil).GetService), name)
}

// GetServiceCounts mocks base method.
func (m *MockManager) GetServiceCounts() (int, int, int, int, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceCounts")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(int)
	ret4, _ := ret[4].(int)
	return ret0, ret1, ret2, ret3, ret4
}

// GetServiceCounts indicates an expected call of GetServiceCounts.
func (mr *MockManagerMockRecorder) GetServiceCounts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceCounts", reflect.TypeOf((*MockManager)(nil).GetServiceCounts))
}

// GetServiceOrder mocks base method.
func (m *MockManager) GetServiceOrder() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceOrder")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetServiceOrder indicates an expected call of GetServiceOrder.
func (mr *MockManagerMockRecorder) GetServiceOrder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceOrder", reflect.TypeOf((*MockManager)(nil).GetServiceOrder))
}

// GetServices mocks base method.
func (m *MockManager) GetServices() map[string]*ServiceStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServices")
	ret0, _ := ret[0].(map[string]*ServiceStatus)
	return ret0
}

// GetServices indicates an expected call of GetServices.
func (mr *MockManagerMockRecorder) GetServices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServices", reflect.TypeOf((*MockManager)(nil).GetServices))
}

// GetTotalServices mocks base method.
func (m *MockManager) GetTotalServices() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalServices")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetTotalServices indicates an expected call of GetTotalServices.
func (mr *MockManagerMockRecorder) GetTotalServices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalServices", reflect.TypeOf((*MockManager)(nil).GetTotalServices))
}

// SetPhase mocks base method.
func (m *MockManager) SetPhase(phase runner.Phase) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPhase", phase)
}

// SetPhase indicates an expected call of SetPhase.
func (mr *MockManagerMockRecorder) SetPhase(phase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPhase", reflect.TypeOf((*MockManager)(nil).SetPhase), phase)
}

// SetTotalServices mocks base method.
func (m *MockManager) SetTotalServices(total int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTotalServices", total)
}

// SetTotalServices indicates an expected call of SetTotalServices.
func (mr *MockManagerMockRecorder) SetTotalServices(total any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTotalServices", reflect.TypeOf((*MockManager)(nil).SetTotalServices), total)
}
