// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/watcher/debouncer.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/watcher/debouncer.go -destination=internal/app/watcher/debouncer_mock.go -package=watcher
//

// Package watcher is a generated GoMock package.
package watcher

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDebouncer is a mock of Debouncer interface.
type MockDebouncer struct {
	ctrl     *gomock.Controller
	recorder *MockDebouncerMockRecorder
	isgomock struct{}
}

// MockDebouncerMockRecorder is the mock recorder for MockDebouncer.
type MockDebouncerMockRecorder struct {
	mock *MockDebouncer
}

// NewMockDebouncer creates a new mock instance.
func NewMockDebouncer(ctrl *gomock.Controller) *MockDebouncer {
	mock := &MockDebouncer{ctrl: ctrl}
	mock.recorder = &MockDebouncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDebouncer) EXPECT() *MockDebouncerMockRecorder {
	return m.recorder
}

// Stop mocks base method.
func (m *MockDebouncer) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockDebouncerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockDebouncer)(nil).Stop))
}

// Trigger mocks base method.
func (m *MockDebouncer) Trigger(file string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Trigger", file)
}

// Trigger indicates an expected call of Trigger.
func (mr *MockDebouncerMockRecorder) Trigger(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trigger", reflect.TypeOf((*MockDebouncer)(nil).Trigger), file)
}
