// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/instance/guard.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/instance/guard.go -destination=internal/app/instance/guard_mock.go -package=instance
//

// Package instance is a generated GoMock package.
package instance

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGuard is a mock of Guard interface.
type MockGuard struct {
	ctrl     *gomock.Controller
	recorder *MockGuardMockRecorder
	isgomock struct{}
}

// MockGuardMockRecorder is the mock recorder for MockGuard.
type MockGuardMockRecorder struct {
	mock *MockGuard
}

// NewMockGuard creates a new mock instance.
func NewMockGuard(ctrl *gomock.Controller) *MockGuard {
	mock := &MockGuard{ctrl: ctrl}
	mock.recorder = &MockGuardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuard) EXPECT() *MockGuardMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockGuard) Check(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockGuardMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockGuard)(nil).Check), ctx)
}
