// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/adapters/process (interfaces: LogSink)
//
// Generated by this command:
//
//	mockgen -destination=internal/adapters/process/streams_mock_test.go -package=process fuku/internal/adapters/process LogSink
//

// Package process is a generated GoMock package.
package process

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogSink is a mock of LogSink interface.
type MockLogSink struct {
	ctrl     *gomock.Controller
	recorder *MockLogSinkMockRecorder
	isgomock struct{}
}

// MockLogSinkMockRecorder is the mock recorder for MockLogSink.
type MockLogSinkMockRecorder struct {
	mock *MockLogSink
}

// NewMockLogSink creates a new mock instance.
func NewMockLogSink(ctrl *gomock.Controller) *MockLogSink {
	mock := &MockLogSink{ctrl: ctrl}
	mock.recorder = &MockLogSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogSink) EXPECT() *MockLogSinkMockRecorder {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockLogSink) Broadcast(service, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Broadcast", service, message)
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockLogSinkMockRecorder) Broadcast(service, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockLogSink)(nil).Broadcast), service, message)
}
