// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/adapters/rest (interfaces: Control,Registry)
//
// Generated by this command:
//
//	mockgen -destination=internal/adapters/rest/handler_mock_test.go -package=rest fuku/internal/adapters/rest Control,Registry
//

// Package rest is a generated GoMock package.
package rest

import (
	services "fuku/internal/app/services"
	model "fuku/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockControl is a mock of Control interface.
type MockControl struct {
	ctrl     *gomock.Controller
	recorder *MockControlMockRecorder
	isgomock struct{}
}

// MockControlMockRecorder is the mock recorder for MockControl.
type MockControlMockRecorder struct {
	mock *MockControl
}

// NewMockControl creates a new mock instance.
func NewMockControl(ctrl *gomock.Controller) *MockControl {
	mock := &MockControl{ctrl: ctrl}
	mock.recorder = &MockControlMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControl) EXPECT() *MockControlMockRecorder {
	return m.recorder
}

// Restart mocks base method.
func (m *MockControl) Restart(id string) (services.Admission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restart", id)
	ret0, _ := ret[0].(services.Admission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restart indicates an expected call of Restart.
func (mr *MockControlMockRecorder) Restart(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockControl)(nil).Restart), id)
}

// Start mocks base method.
func (m *MockControl) Start(id string) (services.Admission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", id)
	ret0, _ := ret[0].(services.Admission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockControlMockRecorder) Start(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockControl)(nil).Start), id)
}

// Stop mocks base method.
func (m *MockControl) Stop(id string) (services.Admission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", id)
	ret0, _ := ret[0].(services.Admission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stop indicates an expected call of Stop.
func (mr *MockControlMockRecorder) Stop(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockControl)(nil).Stop), id)
}

// MockRegistry is a mock of Registry interface.
type MockRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryMockRecorder
	isgomock struct{}
}

// MockRegistryMockRecorder is the mock recorder for MockRegistry.
type MockRegistryMockRecorder struct {
	mock *MockRegistry
}

// NewMockRegistry creates a new mock instance.
func NewMockRegistry(ctrl *gomock.Controller) *MockRegistry {
	mock := &MockRegistry{ctrl: ctrl}
	mock.recorder = &MockRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistry) EXPECT() *MockRegistryMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockRegistry) Read(fn func(*model.Snapshot)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Read", fn)
}

// Read indicates an expected call of Read.
func (mr *MockRegistryMockRecorder) Read(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockRegistry)(nil).Read), fn)
}
