// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/adapters/output (interfaces: Formatter)
//
// Generated by this command:
//
//	mockgen -destination=internal/adapters/output/writer_mock_test.go -package=output fuku/internal/adapters/output Formatter
//

// Package output is a generated GoMock package.
package output

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFormatter is a mock of Formatter interface.
type MockFormatter struct {
	ctrl     *gomock.Controller
	recorder *MockFormatterMockRecorder
	isgomock struct{}
}

// MockFormatterMockRecorder is the mock recorder for MockFormatter.
type MockFormatterMockRecorder struct {
	mock *MockFormatter
}

// NewMockFormatter creates a new mock instance.
func NewMockFormatter(ctrl *gomock.Controller) *MockFormatter {
	mock := &MockFormatter{ctrl: ctrl}
	mock.recorder = &MockFormatterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFormatter) EXPECT() *MockFormatterMockRecorder {
	return m.recorder
}

// FormatServiceLine mocks base method.
func (m *MockFormatter) FormatServiceLine(service, message string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatServiceLine", service, message)
	ret0, _ := ret[0].(string)
	return ret0
}

// FormatServiceLine indicates an expected call of FormatServiceLine.
func (mr *MockFormatterMockRecorder) FormatServiceLine(service, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatServiceLine", reflect.TypeOf((*MockFormatter)(nil).FormatServiceLine), service, message)
}
