// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/cli/tui.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/cli/tui.go -destination=internal/app/cli/tui_mock.go -package=cli
//

// Package cli is a generated GoMock package.
package cli

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTUI is a mock of TUI interface.
type MockTUI struct {
	ctrl     *gomock.Controller
	recorder *MockTUIMockRecorder
	isgomock struct{}
}

// MockTUIMockRecorder is the mock recorder for MockTUI.
type MockTUIMockRecorder struct {
	mock *MockTUI
}

// NewMockTUI creates a new mock instance.
func NewMockTUI(ctrl *gomock.Controller) *MockTUI {
	mock := &MockTUI{ctrl: ctrl}
	mock.recorder = &MockTUIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTUI) EXPECT() *MockTUIMockRecorder {
	return m.recorder
}

// Help mocks base method.
func (m *MockTUI) Help() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Help")
	ret0, _ := ret[0].(error)
	return ret0
}

// Help indicates an expected call of Help.
func (mr *MockTUIMockRecorder) Help() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Help", reflect.TypeOf((*MockTUI)(nil).Help))
}
