// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/cli/tui.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/cli/tui.go -destination=internal/app/cli/tui_mock.go -package=cli
//

// Package cli is a generated GoMock package.
package cli

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTUI is a mock of TUI interface.
type MockTUI struct {
	ctrl     *gomock.Controller
	recorder *MockTUIMockRecorder
	isgomock struct{}
}

// MockTUIMockRecorder is the mock recorder for MockTUI.
type MockTUIMockRecorder struct {
	mock *MockTUI
}

// NewMockTUI creates a new mock instance.
func NewMockTUI(ctrl *gomock.Controller) *MockTUI {
	mock := &MockTUI{ctrl: ctrl}
	mock.recorder = &MockTUIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTUI) EXPECT() *MockTUIMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockTUI) Execute(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockTUIMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTUI)(nil).Execute), ctx)
}
