// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/app/services (interfaces: ProfileResolver,Preflight,Launcher,Tracker,Readiness,Pool,Logger)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/services/run_mock_test.go -package=services fuku/internal/app/services ProfileResolver,Preflight,Launcher,Tracker,Readiness,Pool,Logger
//

// Package services is a generated GoMock package.
package services

import (
	context "context"
	contracts "fuku/internal/contracts"
	model "fuku/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProfileResolver is a mock of ProfileResolver interface.
type MockProfileResolver struct {
	ctrl     *gomock.Controller
	recorder *MockProfileResolverMockRecorder
	isgomock struct{}
}

// MockProfileResolverMockRecorder is the mock recorder for MockProfileResolver.
type MockProfileResolverMockRecorder struct {
	mock *MockProfileResolver
}

// NewMockProfileResolver creates a new mock instance.
func NewMockProfileResolver(ctrl *gomock.Controller) *MockProfileResolver {
	mock := &MockProfileResolver{ctrl: ctrl}
	mock.recorder = &MockProfileResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileResolver) EXPECT() *MockProfileResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockProfileResolver) Resolve(profile string) (model.Tiers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", profile)
	ret0, _ := ret[0].(model.Tiers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockProfileResolverMockRecorder) Resolve(profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockProfileResolver)(nil).Resolve), profile)
}

// MockPreflight is a mock of Preflight interface.
type MockPreflight struct {
	ctrl     *gomock.Controller
	recorder *MockPreflightMockRecorder
	isgomock struct{}
}

// MockPreflightMockRecorder is the mock recorder for MockPreflight.
type MockPreflightMockRecorder struct {
	mock *MockPreflight
}

// NewMockPreflight creates a new mock instance.
func NewMockPreflight(ctrl *gomock.Controller) *MockPreflight {
	mock := &MockPreflight{ctrl: ctrl}
	mock.recorder = &MockPreflightMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreflight) EXPECT() *MockPreflightMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockPreflight) Cleanup(ctx context.Context, dirs map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup", ctx, dirs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockPreflightMockRecorder) Cleanup(ctx, dirs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockPreflight)(nil).Cleanup), ctx, dirs)
}

// MockLauncher is a mock of Launcher interface.
type MockLauncher struct {
	ctrl     *gomock.Controller
	recorder *MockLauncherMockRecorder
	isgomock struct{}
}

// MockLauncherMockRecorder is the mock recorder for MockLauncher.
type MockLauncherMockRecorder struct {
	mock *MockLauncher
}

// NewMockLauncher creates a new mock instance.
func NewMockLauncher(ctrl *gomock.Controller) *MockLauncher {
	mock := &MockLauncher{ctrl: ctrl}
	mock.recorder = &MockLauncherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLauncher) EXPECT() *MockLauncherMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockLauncher) Start(svc model.Service) (contracts.Process, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", svc)
	ret0, _ := ret[0].(contracts.Process)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockLauncherMockRecorder) Start(svc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockLauncher)(nil).Start), svc)
}

// MockTracker is a mock of Tracker interface.
type MockTracker struct {
	ctrl     *gomock.Controller
	recorder *MockTrackerMockRecorder
	isgomock struct{}
}

// MockTrackerMockRecorder is the mock recorder for MockTracker.
type MockTrackerMockRecorder struct {
	mock *MockTracker
}

// NewMockTracker creates a new mock instance.
func NewMockTracker(ctrl *gomock.Controller) *MockTracker {
	mock := &MockTracker{ctrl: ctrl}
	mock.recorder = &MockTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracker) EXPECT() *MockTrackerMockRecorder {
	return m.recorder
}

// Detach mocks base method.
func (m *MockTracker) Detach(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Detach", id)
}

// Detach indicates an expected call of Detach.
func (mr *MockTrackerMockRecorder) Detach(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detach", reflect.TypeOf((*MockTracker)(nil).Detach), id)
}

// Get mocks base method.
func (m *MockTracker) Get(id string) (contracts.Process, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(contracts.Process)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTrackerMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTracker)(nil).Get), id)
}

// Reverse mocks base method.
func (m *MockTracker) Reverse() []contracts.Process {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reverse")
	ret0, _ := ret[0].([]contracts.Process)
	return ret0
}

// Reverse indicates an expected call of Reverse.
func (mr *MockTrackerMockRecorder) Reverse() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reverse", reflect.TypeOf((*MockTracker)(nil).Reverse))
}

// Untrack mocks base method.
func (m *MockTracker) Untrack(id string, proc contracts.Process) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Untrack", id, proc)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Untrack indicates an expected call of Untrack.
func (mr *MockTrackerMockRecorder) Untrack(id, proc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Untrack", reflect.TypeOf((*MockTracker)(nil).Untrack), id, proc)
}

// MockReadiness is a mock of Readiness interface.
type MockReadiness struct {
	ctrl     *gomock.Controller
	recorder *MockReadinessMockRecorder
	isgomock struct{}
}

// MockReadinessMockRecorder is the mock recorder for MockReadiness.
type MockReadinessMockRecorder struct {
	mock *MockReadiness
}

// NewMockReadiness creates a new mock instance.
func NewMockReadiness(ctrl *gomock.Controller) *MockReadiness {
	mock := &MockReadiness{ctrl: ctrl}
	mock.recorder = &MockReadinessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadiness) EXPECT() *MockReadinessMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockReadiness) Check(ctx context.Context, readiness model.Readiness, proc contracts.Process) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, readiness, proc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockReadinessMockRecorder) Check(ctx, readiness, proc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockReadiness)(nil).Check), ctx, readiness, proc)
}

// ProbePort mocks base method.
func (m *MockReadiness) ProbePort(readiness model.Readiness) model.Port {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProbePort", readiness)
	ret0, _ := ret[0].(model.Port)
	return ret0
}

// ProbePort indicates an expected call of ProbePort.
func (mr *MockReadinessMockRecorder) ProbePort(readiness any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProbePort", reflect.TypeOf((*MockReadiness)(nil).ProbePort), readiness)
}

// MockPool is a mock of Pool interface.
type MockPool struct {
	ctrl     *gomock.Controller
	recorder *MockPoolMockRecorder
	isgomock struct{}
}

// MockPoolMockRecorder is the mock recorder for MockPool.
type MockPoolMockRecorder struct {
	mock *MockPool
}

// NewMockPool creates a new mock instance.
func NewMockPool(ctrl *gomock.Controller) *MockPool {
	mock := &MockPool{ctrl: ctrl}
	mock.recorder = &MockPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPool) EXPECT() *MockPoolMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockPool) Acquire(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Acquire indicates an expected call of Acquire.
func (mr *MockPoolMockRecorder) Acquire(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockPool)(nil).Acquire), ctx)
}

// Release mocks base method.
func (m *MockPool) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockPoolMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockPool)(nil).Release))
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), varargs...)
}

// Error mocks base method.
func (m *MockLogger) Error(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), varargs...)
}

// Info mocks base method.
func (m *MockLogger) Info(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), varargs...)
}

// Warn mocks base method.
func (m *MockLogger) Warn(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), varargs...)
}
