// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/ui/services/controller.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/ui/services/controller.go -destination=internal/app/ui/services/controller_mock.go -package=services
//

// Package services is a generated GoMock package.
package services

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
	isgomock struct{}
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// Restart mocks base method.
func (m *MockController) Restart(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restart", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Restart indicates an expected call of Restart.
func (mr *MockControllerMockRecorder) Restart(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockController)(nil).Restart), name)
}

// Start mocks base method.
func (m *MockController) Start(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockControllerMockRecorder) Start(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockController)(nil).Start), name)
}

// Stop mocks base method.
func (m *MockController) Stop(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockControllerMockRecorder) Stop(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockController)(nil).Stop), name)
}

// StopAll mocks base method.
func (m *MockController) StopAll() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StopAll")
}

// StopAll indicates an expected call of StopAll.
func (mr *MockControllerMockRecorder) StopAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopAll", reflect.TypeOf((*MockController)(nil).StopAll))
}
