// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/adapters/detach (interfaces: Starter,View)
//
// Generated by this command:
//
//	mockgen -destination=internal/adapters/detach/command_mock_test.go -package=detach fuku/internal/adapters/detach Starter,View
//

// Package detach is a generated GoMock package.
package detach

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStarter is a mock of Starter interface.
type MockStarter struct {
	ctrl     *gomock.Controller
	recorder *MockStarterMockRecorder
	isgomock struct{}
}

// MockStarterMockRecorder is the mock recorder for MockStarter.
type MockStarterMockRecorder struct {
	mock *MockStarter
}

// NewMockStarter creates a new mock instance.
func NewMockStarter(ctrl *gomock.Controller) *MockStarter {
	mock := &MockStarter{ctrl: ctrl}
	mock.recorder = &MockStarterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStarter) EXPECT() *MockStarterMockRecorder {
	return m.recorder
}

// Launch mocks base method.
func (m *MockStarter) Launch() (Process, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Launch")
	ret0, _ := ret[0].(Process)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Launch indicates an expected call of Launch.
func (mr *MockStarterMockRecorder) Launch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Launch", reflect.TypeOf((*MockStarter)(nil).Launch))
}

// MockView is a mock of View interface.
type MockView struct {
	ctrl     *gomock.Controller
	recorder *MockViewMockRecorder
	isgomock struct{}
}

// MockViewMockRecorder is the mock recorder for MockView.
type MockViewMockRecorder struct {
	mock *MockView
}

// NewMockView creates a new mock instance.
func NewMockView(ctrl *gomock.Controller) *MockView {
	mock := &MockView{ctrl: ctrl}
	mock.recorder = &MockViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockView) EXPECT() *MockViewMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockView) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockViewMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockView)(nil).Close))
}

// Open mocks base method.
func (m *MockView) Open() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Open")
}

// Open indicates an expected call of Open.
func (mr *MockViewMockRecorder) Open() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockView)(nil).Open))
}

// Show mocks base method.
func (m *MockView) Show(record Record) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Show", record)
}

// Show indicates an expected call of Show.
func (mr *MockViewMockRecorder) Show(record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Show", reflect.TypeOf((*MockView)(nil).Show), record)
}
