// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/adapters/detach (interfaces: StatusSource)
//
// Generated by this command:
//
//	mockgen -destination=internal/adapters/detach/stop_mock_test.go -package=detach fuku/internal/adapters/detach StatusSource
//

// Package detach is a generated GoMock package.
package detach

import (
	contracts "fuku/internal/contracts"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStatusSource is a mock of StatusSource interface.
type MockStatusSource struct {
	ctrl     *gomock.Controller
	recorder *MockStatusSourceMockRecorder
	isgomock struct{}
}

// MockStatusSourceMockRecorder is the mock recorder for MockStatusSource.
type MockStatusSourceMockRecorder struct {
	mock *MockStatusSource
}

// NewMockStatusSource creates a new mock instance.
func NewMockStatusSource(ctrl *gomock.Controller) *MockStatusSource {
	mock := &MockStatusSource{ctrl: ctrl}
	mock.recorder = &MockStatusSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusSource) EXPECT() *MockStatusSourceMockRecorder {
	return m.recorder
}

// Status mocks base method.
func (m *MockStatusSource) Status() (contracts.LogStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(contracts.LogStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockStatusSourceMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockStatusSource)(nil).Status))
}
