// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/adapters/detach (interfaces: Socket)
//
// Generated by this command:
//
//	mockgen -destination=internal/adapters/detach/stop_mock_test.go -package=detach fuku/internal/adapters/detach Socket
//

// Package detach is a generated GoMock package.
package detach

import (
	contracts "fuku/internal/contracts"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSocket is a mock of Socket interface.
type MockSocket struct {
	ctrl     *gomock.Controller
	recorder *MockSocketMockRecorder
	isgomock struct{}
}

// MockSocketMockRecorder is the mock recorder for MockSocket.
type MockSocketMockRecorder struct {
	mock *MockSocket
}

// NewMockSocket creates a new mock instance.
func NewMockSocket(ctrl *gomock.Controller) *MockSocket {
	mock := &MockSocket{ctrl: ctrl}
	mock.recorder = &MockSocketMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSocket) EXPECT() *MockSocketMockRecorder {
	return m.recorder
}

// RequestStop mocks base method.
func (m *MockSocket) RequestStop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestStop")
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestStop indicates an expected call of RequestStop.
func (mr *MockSocketMockRecorder) RequestStop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestStop", reflect.TypeOf((*MockSocket)(nil).RequestStop))
}

// Status mocks base method.
func (m *MockSocket) Status() (contracts.LogStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(contracts.LogStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockSocketMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockSocket)(nil).Status))
}
