// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/runtime/commands.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/runtime/commands.go -destination=internal/app/runtime/commands_mock.go -package=runtime
//

// Package runtime is a generated GoMock package.
package runtime

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCommandBus is a mock of CommandBus interface.
type MockCommandBus struct {
	ctrl     *gomock.Controller
	recorder *MockCommandBusMockRecorder
	isgomock struct{}
}

// MockCommandBusMockRecorder is the mock recorder for MockCommandBus.
type MockCommandBusMockRecorder struct {
	mock *MockCommandBus
}

// NewMockCommandBus creates a new mock instance.
func NewMockCommandBus(ctrl *gomock.Controller) *MockCommandBus {
	mock := &MockCommandBus{ctrl: ctrl}
	mock.recorder = &MockCommandBusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandBus) EXPECT() *MockCommandBusMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCommandBus) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockCommandBusMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCommandBus)(nil).Close))
}

// Publish mocks base method.
func (m *MockCommandBus) Publish(cmd Command) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", cmd)
}

// Publish indicates an expected call of Publish.
func (mr *MockCommandBusMockRecorder) Publish(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockCommandBus)(nil).Publish), cmd)
}

// Subscribe mocks base method.
func (m *MockCommandBus) Subscribe(ctx context.Context) <-chan Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx)
	ret0, _ := ret[0].(<-chan Command)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockCommandBusMockRecorder) Subscribe(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockCommandBus)(nil).Subscribe), ctx)
}
