// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/runtime/logwriter.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/runtime/logwriter.go -destination=internal/app/runtime/logwriter_mock.go -package=runtime
//

// Package runtime is a generated GoMock package.
package runtime

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogFilter is a mock of LogFilter interface.
type MockLogFilter struct {
	ctrl     *gomock.Controller
	recorder *MockLogFilterMockRecorder
	isgomock struct{}
}

// MockLogFilterMockRecorder is the mock recorder for MockLogFilter.
type MockLogFilterMockRecorder struct {
	mock *MockLogFilter
}

// NewMockLogFilter creates a new mock instance.
func NewMockLogFilter(ctrl *gomock.Controller) *MockLogFilter {
	mock := &MockLogFilter{ctrl: ctrl}
	mock.recorder = &MockLogFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogFilter) EXPECT() *MockLogFilterMockRecorder {
	return m.recorder
}

// IsEnabled mocks base method.
func (m *MockLogFilter) IsEnabled(service string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled", service)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockLogFilterMockRecorder) IsEnabled(service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockLogFilter)(nil).IsEnabled), service)
}

// MockLogWriter is a mock of LogWriter interface.
type MockLogWriter struct {
	ctrl     *gomock.Controller
	recorder *MockLogWriterMockRecorder
	isgomock struct{}
}

// MockLogWriterMockRecorder is the mock recorder for MockLogWriter.
type MockLogWriterMockRecorder struct {
	mock *MockLogWriter
}

// NewMockLogWriter creates a new mock instance.
func NewMockLogWriter(ctrl *gomock.Controller) *MockLogWriter {
	mock := &MockLogWriter{ctrl: ctrl}
	mock.recorder = &MockLogWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogWriter) EXPECT() *MockLogWriterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockLogWriter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockLogWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockLogWriter)(nil).Close))
}

// Start mocks base method.
func (m *MockLogWriter) Start(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx)
}

// Start indicates an expected call of Start.
func (mr *MockLogWriterMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockLogWriter)(nil).Start), ctx)
}
