// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/app/logs (interfaces: Handler)
//
// Generated by this command:
//
//	mockgen -destination=internal/adapters/logsocket/client_mock_test.go -package=logsocket fuku/internal/app/logs Handler
//

// Package logsocket is a generated GoMock package.
package logsocket

import (
	contracts "fuku/internal/contracts"
	model "fuku/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// HandleLog mocks base method.
func (m *MockHandler) HandleLog(line model.LogLine) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleLog", line)
}

// HandleLog indicates an expected call of HandleLog.
func (mr *MockHandlerMockRecorder) HandleLog(line any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLog", reflect.TypeOf((*MockHandler)(nil).HandleLog), line)
}

// HandleStatus mocks base method.
func (m *MockHandler) HandleStatus(status contracts.LogStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleStatus", status)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleStatus indicates an expected call of HandleStatus.
func (mr *MockHandlerMockRecorder) HandleStatus(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleStatus", reflect.TypeOf((*MockHandler)(nil).HandleStatus), status)
}
