// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/platform/bus (interfaces: FailureReporter,Logger)
//
// Generated by this command:
//
//	mockgen -destination=internal/platform/bus/bus_mock_test.go -package=bus fuku/internal/platform/bus FailureReporter,Logger
//

// Package bus is a generated GoMock package.
package bus

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFailureReporter is a mock of FailureReporter interface.
type MockFailureReporter struct {
	ctrl     *gomock.Controller
	recorder *MockFailureReporterMockRecorder
	isgomock struct{}
}

// MockFailureReporterMockRecorder is the mock recorder for MockFailureReporter.
type MockFailureReporterMockRecorder struct {
	mock *MockFailureReporter
}

// NewMockFailureReporter creates a new mock instance.
func NewMockFailureReporter(ctrl *gomock.Controller) *MockFailureReporter {
	mock := &MockFailureReporter{ctrl: ctrl}
	mock.recorder = &MockFailureReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFailureReporter) EXPECT() *MockFailureReporterMockRecorder {
	return m.recorder
}

// Fail mocks base method.
func (m *MockFailureReporter) Fail(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Fail", err)
}

// Fail indicates an expected call of Fail.
func (mr *MockFailureReporterMockRecorder) Fail(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fail", reflect.TypeOf((*MockFailureReporter)(nil).Fail), err)
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockLogger) Error(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), varargs...)
}

// Warn mocks base method.
func (m *MockLogger) Warn(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), varargs...)
}
