// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/discovery/discovery.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/discovery/discovery.go -destination=internal/app/discovery/discovery_mock.go -package=discovery
//

// Package discovery is a generated GoMock package.
package discovery

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDiscovery is a mock of Discovery interface.
type MockDiscovery struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoveryMockRecorder
	isgomock struct{}
}

// MockDiscoveryMockRecorder is the mock recorder for MockDiscovery.
type MockDiscoveryMockRecorder struct {
	mock *MockDiscovery
}

// NewMockDiscovery creates a new mock instance.
func NewMockDiscovery(ctrl *gomock.Controller) *MockDiscovery {
	mock := &MockDiscovery{ctrl: ctrl}
	mock.recorder = &MockDiscoveryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscovery) EXPECT() *MockDiscoveryMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockDiscovery) Resolve(profile string) ([]Tier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", profile)
	ret0, _ := ret[0].([]Tier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockDiscoveryMockRecorder) Resolve(profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockDiscovery)(nil).Resolve), profile)
}
