// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/adapters/cli (interfaces: Formatter)
//
// Generated by this command:
//
//	mockgen -destination=internal/adapters/cli/logview_mock_test.go -package=cli fuku/internal/adapters/cli Formatter
//

// Package cli is a generated GoMock package.
package cli

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFormatter is a mock of Formatter interface.
type MockFormatter struct {
	ctrl     *gomock.Controller
	recorder *MockFormatterMockRecorder
	isgomock struct{}
}

// MockFormatterMockRecorder is the mock recorder for MockFormatter.
type MockFormatterMockRecorder struct {
	mock *MockFormatter
}

// NewMockFormatter creates a new mock instance.
func NewMockFormatter(ctrl *gomock.Controller) *MockFormatter {
	mock := &MockFormatter{ctrl: ctrl}
	mock.recorder = &MockFormatterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFormatter) EXPECT() *MockFormatterMockRecorder {
	return m.recorder
}

// FormatMessage mocks base method.
func (m *MockFormatter) FormatMessage(service, message string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatMessage", service, message)
	ret0, _ := ret[0].(string)
	return ret0
}

// FormatMessage indicates an expected call of FormatMessage.
func (mr *MockFormatterMockRecorder) FormatMessage(service, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatMessage", reflect.TypeOf((*MockFormatter)(nil).FormatMessage), service, message)
}
