// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/getsentry/sentry-go (interfaces: Transport)
//
// Generated by this command:
//
//	mockgen -destination=internal/adapters/telemetry/sentry_mock_test.go -package=telemetry github.com/getsentry/sentry-go Transport
//

// Package telemetry is a generated GoMock package.
package telemetry

import (
	context "context"
	reflect "reflect"
	time "time"

	sentry "github.com/getsentry/sentry-go"
	gomock "go.uber.org/mock/gomock"
)

// MockTransport is a mock of Transport interface.
type MockTransport struct {
	ctrl     *gomock.Controller
	recorder *MockTransportMockRecorder
	isgomock struct{}
}

// MockTransportMockRecorder is the mock recorder for MockTransport.
type MockTransportMockRecorder struct {
	mock *MockTransport
}

// NewMockTransport creates a new mock instance.
func NewMockTransport(ctrl *gomock.Controller) *MockTransport {
	mock := &MockTransport{ctrl: ctrl}
	mock.recorder = &MockTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransport) EXPECT() *MockTransportMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockTransport) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockTransportMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTransport)(nil).Close))
}

// Configure mocks base method.
func (m *MockTransport) Configure(options sentry.ClientOptions) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Configure", options)
}

// Configure indicates an expected call of Configure.
func (mr *MockTransportMockRecorder) Configure(options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configure", reflect.TypeOf((*MockTransport)(nil).Configure), options)
}

// Flush mocks base method.
func (m *MockTransport) Flush(timeout time.Duration) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", timeout)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockTransportMockRecorder) Flush(timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockTransport)(nil).Flush), timeout)
}

// FlushWithContext mocks base method.
func (m *MockTransport) FlushWithContext(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushWithContext", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// FlushWithContext indicates an expected call of FlushWithContext.
func (mr *MockTransportMockRecorder) FlushWithContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushWithContext", reflect.TypeOf((*MockTransport)(nil).FlushWithContext), ctx)
}

// SendEvent mocks base method.
func (m *MockTransport) SendEvent(event *sentry.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendEvent", event)
}

// SendEvent indicates an expected call of SendEvent.
func (mr *MockTransportMockRecorder) SendEvent(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEvent", reflect.TypeOf((*MockTransport)(nil).SendEvent), event)
}
