// Code generated by MockGen. DO NOT EDIT.
// Source: go.uber.org/fx (interfaces: Shutdowner,Lifecycle)
//
// Generated by this command:
//
//	mockgen -destination=internal/bootstrap/lifecycle/fx_mock_test.go -package=lifecycle go.uber.org/fx Shutdowner,Lifecycle
//

// Package lifecycle is a generated GoMock package.
package lifecycle

import (
	reflect "reflect"

	fx "go.uber.org/fx"
	gomock "go.uber.org/mock/gomock"
)

// MockShutdowner is a mock of Shutdowner interface.
type MockShutdowner struct {
	ctrl     *gomock.Controller
	recorder *MockShutdownerMockRecorder
	isgomock struct{}
}

// MockShutdownerMockRecorder is the mock recorder for MockShutdowner.
type MockShutdownerMockRecorder struct {
	mock *MockShutdowner
}

// NewMockShutdowner creates a new mock instance.
func NewMockShutdowner(ctrl *gomock.Controller) *MockShutdowner {
	mock := &MockShutdowner{ctrl: ctrl}
	mock.recorder = &MockShutdownerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShutdowner) EXPECT() *MockShutdownerMockRecorder {
	return m.recorder
}

// Shutdown mocks base method.
func (m *MockShutdowner) Shutdown(arg0 ...fx.ShutdownOption) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Shutdown", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockShutdownerMockRecorder) Shutdown(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockShutdowner)(nil).Shutdown), arg0...)
}

// MockLifecycle is a mock of Lifecycle interface.
type MockLifecycle struct {
	ctrl     *gomock.Controller
	recorder *MockLifecycleMockRecorder
	isgomock struct{}
}

// MockLifecycleMockRecorder is the mock recorder for MockLifecycle.
type MockLifecycleMockRecorder struct {
	mock *MockLifecycle
}

// NewMockLifecycle creates a new mock instance.
func NewMockLifecycle(ctrl *gomock.Controller) *MockLifecycle {
	mock := &MockLifecycle{ctrl: ctrl}
	mock.recorder = &MockLifecycleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLifecycle) EXPECT() *MockLifecycleMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockLifecycle) Append(arg0 fx.Hook) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Append", arg0)
}

// Append indicates an expected call of Append.
func (mr *MockLifecycleMockRecorder) Append(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockLifecycle)(nil).Append), arg0)
}
