// Code generated by MockGen. DO NOT EDIT.
// Source: internal/config/logger/event.go
//
// Generated by this command:
//
//	mockgen -source=internal/config/logger/event.go -destination=internal/config/logger/event_mock.go -package=logger
//

// Package logger is a generated GoMock package.
package logger

import (
	bytes "bytes"
	reflect "reflect"

	zerolog "github.com/rs/zerolog"
	gomock "go.uber.org/mock/gomock"
)

// MockEventLogger is a mock of EventLogger interface.
type MockEventLogger struct {
	ctrl     *gomock.Controller
	recorder *MockEventLoggerMockRecorder
	isgomock struct{}
}

// MockEventLoggerMockRecorder is the mock recorder for MockEventLogger.
type MockEventLoggerMockRecorder struct {
	mock *MockEventLogger
}

// NewMockEventLogger creates a new mock instance.
func NewMockEventLogger(ctrl *gomock.Controller) *MockEventLogger {
	mock := &MockEventLogger{ctrl: ctrl}
	mock.recorder = &MockEventLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventLogger) EXPECT() *MockEventLoggerMockRecorder {
	return m.recorder
}

// NewLogger mocks base method.
func (m *MockEventLogger) NewLogger(buf *bytes.Buffer) zerolog.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewLogger", buf)
	ret0, _ := ret[0].(zerolog.Logger)
	return ret0
}

// NewLogger indicates an expected call of NewLogger.
func (mr *MockEventLoggerMockRecorder) NewLogger(buf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewLogger", reflect.TypeOf((*MockEventLogger)(nil).NewLogger), buf)
}
