// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/dotenv/dotenv.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/dotenv/dotenv.go -destination=internal/app/dotenv/dotenv_mock.go -package=dotenv
//

// Package dotenv is a generated GoMock package.
package dotenv

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLoader is a mock of Loader interface.
type MockLoader struct {
	ctrl     *gomock.Controller
	recorder *MockLoaderMockRecorder
	isgomock struct{}
}

// MockLoaderMockRecorder is the mock recorder for MockLoader.
type MockLoaderMockRecorder struct {
	mock *MockLoader
}

// NewMockLoader creates a new mock instance.
func NewMockLoader(ctrl *gomock.Controller) *MockLoader {
	mock := &MockLoader{ctrl: ctrl}
	mock.recorder = &MockLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoader) EXPECT() *MockLoaderMockRecorder {
	return m.recorder
}

// Env mocks base method.
func (m *MockLoader) Env(id string) []Store {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Env", id)
	ret0, _ := ret[0].([]Store)
	return ret0
}

// Env indicates an expected call of Env.
func (mr *MockLoaderMockRecorder) Env(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Env", reflect.TypeOf((*MockLoader)(nil).Env), id)
}

// Run mocks base method.
func (m *MockLoader) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockLoaderMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockLoader)(nil).Run), ctx)
}
