// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/registry/registry.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/registry/registry.go -destination=internal/app/registry/registry_mock.go -package=registry
//

// Package registry is a generated GoMock package.
package registry

import (
	bus "fuku/internal/app/bus"
	process "fuku/internal/app/process"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRegistry is a mock of Registry interface.
type MockRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryMockRecorder
	isgomock struct{}
}

// MockRegistryMockRecorder is the mock recorder for MockRegistry.
type MockRegistryMockRecorder struct {
	mock *MockRegistry
}

// NewMockRegistry creates a new mock instance.
func NewMockRegistry(ctrl *gomock.Controller) *MockRegistry {
	mock := &MockRegistry{ctrl: ctrl}
	mock.recorder = &MockRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistry) EXPECT() *MockRegistryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRegistry) Add(tier string, svc bus.Service, proc process.Process) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", tier, svc, proc)
}

// Add indicates an expected call of Add.
func (mr *MockRegistryMockRecorder) Add(tier, svc, proc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRegistry)(nil).Add), tier, svc, proc)
}

// Detach mocks base method.
func (m *MockRegistry) Detach(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Detach", id)
}

// Detach indicates an expected call of Detach.
func (mr *MockRegistryMockRecorder) Detach(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detach", reflect.TypeOf((*MockRegistry)(nil).Detach), id)
}

// Get mocks base method.
func (m *MockRegistry) Get(id string) Lookup {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(Lookup)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockRegistryMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRegistry)(nil).Get), id)
}

// Remove mocks base method.
func (m *MockRegistry) Remove(id string, proc process.Process) RemoveResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", id, proc)
	ret0, _ := ret[0].(RemoveResult)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRegistryMockRecorder) Remove(id, proc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRegistry)(nil).Remove), id, proc)
}

// SnapshotReverse mocks base method.
func (m *MockRegistry) SnapshotReverse() []ProcessEntry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotReverse")
	ret0, _ := ret[0].([]ProcessEntry)
	return ret0
}

// SnapshotReverse indicates an expected call of SnapshotReverse.
func (mr *MockRegistryMockRecorder) SnapshotReverse() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotReverse", reflect.TypeOf((*MockRegistry)(nil).SnapshotReverse))
}

// Wait mocks base method.
func (m *MockRegistry) Wait() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Wait")
}

// Wait indicates an expected call of Wait.
func (mr *MockRegistryMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockRegistry)(nil).Wait))
}
