// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/registry/store.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/registry/store.go -destination=internal/app/registry/store_mock.go -package=registry
//

// Package registry is a generated GoMock package.
package registry

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Counts mocks base method.
func (m *MockStore) Counts() StatusCounts {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Counts")
	ret0, _ := ret[0].(StatusCounts)
	return ret0
}

// Counts indicates an expected call of Counts.
func (mr *MockStoreMockRecorder) Counts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Counts", reflect.TypeOf((*MockStore)(nil).Counts))
}

// Phase mocks base method.
func (m *MockStore) Phase() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Phase")
	ret0, _ := ret[0].(string)
	return ret0
}

// Phase indicates an expected call of Phase.
func (mr *MockStoreMockRecorder) Phase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Phase", reflect.TypeOf((*MockStore)(nil).Phase))
}

// Profile mocks base method.
func (m *MockStore) Profile() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile")
	ret0, _ := ret[0].(string)
	return ret0
}

// Profile indicates an expected call of Profile.
func (mr *MockStoreMockRecorder) Profile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockStore)(nil).Profile))
}

// Run mocks base method.
func (m *MockStore) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockStoreMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockStore)(nil).Run), ctx)
}

// Service mocks base method.
func (m *MockStore) Service(id string) (ServiceSnapshot, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Service", id)
	ret0, _ := ret[0].(ServiceSnapshot)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Service indicates an expected call of Service.
func (mr *MockStoreMockRecorder) Service(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Service", reflect.TypeOf((*MockStore)(nil).Service), id)
}

// Services mocks base method.
func (m *MockStore) Services() []ServiceSnapshot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Services")
	ret0, _ := ret[0].([]ServiceSnapshot)
	return ret0
}

// Services indicates an expected call of Services.
func (mr *MockStoreMockRecorder) Services() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Services", reflect.TypeOf((*MockStore)(nil).Services))
}

// Uptime mocks base method.
func (m *MockStore) Uptime() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Uptime")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Uptime indicates an expected call of Uptime.
func (mr *MockStoreMockRecorder) Uptime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Uptime", reflect.TypeOf((*MockStore)(nil).Uptime))
}

// WaitReady mocks base method.
func (m *MockStore) WaitReady() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WaitReady")
}

// WaitReady indicates an expected call of WaitReady.
func (mr *MockStoreMockRecorder) WaitReady() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitReady", reflect.TypeOf((*MockStore)(nil).WaitReady))
}

// MockserviceIdentifier is a mock of serviceIdentifier interface.
type MockserviceIdentifier struct {
	ctrl     *gomock.Controller
	recorder *MockserviceIdentifierMockRecorder
	isgomock struct{}
}

// MockserviceIdentifierMockRecorder is the mock recorder for MockserviceIdentifier.
type MockserviceIdentifierMockRecorder struct {
	mock *MockserviceIdentifier
}

// NewMockserviceIdentifier creates a new mock instance.
func NewMockserviceIdentifier(ctrl *gomock.Controller) *MockserviceIdentifier {
	mock := &MockserviceIdentifier{ctrl: ctrl}
	mock.recorder = &MockserviceIdentifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockserviceIdentifier) EXPECT() *MockserviceIdentifierMockRecorder {
	return m.recorder
}

// ServiceID mocks base method.
func (m *MockserviceIdentifier) ServiceID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ServiceID indicates an expected call of ServiceID.
func (mr *MockserviceIdentifierMockRecorder) ServiceID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceID", reflect.TypeOf((*MockserviceIdentifier)(nil).ServiceID))
}
