// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/registry/store.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/registry/store.go -destination=internal/app/registry/store_mock.go -package=registry
//

// Package registry is a generated GoMock package.
package registry

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Phase mocks base method.
func (m *MockStore) Phase() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Phase")
	ret0, _ := ret[0].(string)
	return ret0
}

// Phase indicates an expected call of Phase.
func (mr *MockStoreMockRecorder) Phase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Phase", reflect.TypeOf((*MockStore)(nil).Phase))
}

// Profile mocks base method.
func (m *MockStore) Profile() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile")
	ret0, _ := ret[0].(string)
	return ret0
}

// Profile indicates an expected call of Profile.
func (mr *MockStoreMockRecorder) Profile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockStore)(nil).Profile))
}

// Run mocks base method.
func (m *MockStore) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockStoreMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockStore)(nil).Run), ctx)
}

// Service mocks base method.
func (m *MockStore) Service(name string) (ServiceSnapshot, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Service", name)
	ret0, _ := ret[0].(ServiceSnapshot)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Service indicates an expected call of Service.
func (mr *MockStoreMockRecorder) Service(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Service", reflect.TypeOf((*MockStore)(nil).Service), name)
}

// ServiceByID mocks base method.
func (m *MockStore) ServiceByID(id string) (ServiceSnapshot, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceByID", id)
	ret0, _ := ret[0].(ServiceSnapshot)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ServiceByID indicates an expected call of ServiceByID.
func (mr *MockStoreMockRecorder) ServiceByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceByID", reflect.TypeOf((*MockStore)(nil).ServiceByID), id)
}

// Services mocks base method.
func (m *MockStore) Services() []ServiceSnapshot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Services")
	ret0, _ := ret[0].([]ServiceSnapshot)
	return ret0
}

// Services indicates an expected call of Services.
func (mr *MockStoreMockRecorder) Services() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Services", reflect.TypeOf((*MockStore)(nil).Services))
}

// Uptime mocks base method.
func (m *MockStore) Uptime() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Uptime")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Uptime indicates an expected call of Uptime.
func (mr *MockStoreMockRecorder) Uptime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Uptime", reflect.TypeOf((*MockStore)(nil).Uptime))
}

// WaitReady mocks base method.
func (m *MockStore) WaitReady() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WaitReady")
}

// WaitReady indicates an expected call of WaitReady.
func (mr *MockStoreMockRecorder) WaitReady() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitReady", reflect.TypeOf((*MockStore)(nil).WaitReady))
}

// MockserviceNamer is a mock of serviceNamer interface.
type MockserviceNamer struct {
	ctrl     *gomock.Controller
	recorder *MockserviceNamerMockRecorder
	isgomock struct{}
}

// MockserviceNamerMockRecorder is the mock recorder for MockserviceNamer.
type MockserviceNamerMockRecorder struct {
	mock *MockserviceNamer
}

// NewMockserviceNamer creates a new mock instance.
func NewMockserviceNamer(ctrl *gomock.Controller) *MockserviceNamer {
	mock := &MockserviceNamer{ctrl: ctrl}
	mock.recorder = &MockserviceNamerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockserviceNamer) EXPECT() *MockserviceNamerMockRecorder {
	return m.recorder
}

// ServiceName mocks base method.
func (m *MockserviceNamer) ServiceName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceName")
	ret0, _ := ret[0].(string)
	return ret0
}

// ServiceName indicates an expected call of ServiceName.
func (mr *MockserviceNamerMockRecorder) ServiceName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceName", reflect.TypeOf((*MockserviceNamer)(nil).ServiceName))
}
