// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/relay/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/relay/client.go -destination=internal/app/relay/client_mock.go -package=relay
//

// Package relay is a generated GoMock package.
package relay

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// HandleLog mocks base method.
func (m *MockHandler) HandleLog(arg0 LogMessage) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleLog", arg0)
}

// HandleLog indicates an expected call of HandleLog.
func (mr *MockHandlerMockRecorder) HandleLog(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLog", reflect.TypeOf((*MockHandler)(nil).HandleLog), arg0)
}

// HandleStatus mocks base method.
func (m *MockHandler) HandleStatus(arg0 StatusMessage) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleStatus", arg0)
}

// HandleStatus indicates an expected call of HandleStatus.
func (mr *MockHandlerMockRecorder) HandleStatus(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleStatus", reflect.TypeOf((*MockHandler)(nil).HandleStatus), arg0)
}

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// Connect mocks base method.
func (m *MockClient) Connect(socketPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", socketPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockClientMockRecorder) Connect(socketPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockClient)(nil).Connect), socketPath)
}

// Stream mocks base method.
func (m *MockClient) Stream(ctx context.Context, handler Handler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stream", ctx, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stream indicates an expected call of Stream.
func (mr *MockClientMockRecorder) Stream(ctx, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockClient)(nil).Stream), ctx, handler)
}

// Subscribe mocks base method.
func (m *MockClient) Subscribe(services []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", services)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockClientMockRecorder) Subscribe(services any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockClient)(nil).Subscribe), services)
}
