// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/logs/hub.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/logs/hub.go -destination=internal/app/logs/hub_mock.go -package=logs
//

// Package logs is a generated GoMock package.
package logs

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHub is a mock of Hub interface.
type MockHub struct {
	ctrl     *gomock.Controller
	recorder *MockHubMockRecorder
	isgomock struct{}
}

// MockHubMockRecorder is the mock recorder for MockHub.
type MockHubMockRecorder struct {
	mock *MockHub
}

// NewMockHub creates a new mock instance.
func NewMockHub(ctrl *gomock.Controller) *MockHub {
	mock := &MockHub{ctrl: ctrl}
	mock.recorder = &MockHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHub) EXPECT() *MockHubMockRecorder {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockHub) Broadcast(service, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Broadcast", service, message)
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockHubMockRecorder) Broadcast(service, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockHub)(nil).Broadcast), service, message)
}

// NewClientConn mocks base method.
func (m *MockHub) NewClientConn(id string) *ClientConn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewClientConn", id)
	ret0, _ := ret[0].(*ClientConn)
	return ret0
}

// NewClientConn indicates an expected call of NewClientConn.
func (mr *MockHubMockRecorder) NewClientConn(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClientConn", reflect.TypeOf((*MockHub)(nil).NewClientConn), id)
}

// Register mocks base method.
func (m *MockHub) Register(conn *ClientConn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", conn)
}

// Register indicates an expected call of Register.
func (mr *MockHubMockRecorder) Register(conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockHub)(nil).Register), conn)
}

// Run mocks base method.
func (m *MockHub) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockHubMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockHub)(nil).Run), ctx)
}

// Unregister mocks base method.
func (m *MockHub) Unregister(conn *ClientConn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unregister", conn)
}

// Unregister indicates an expected call of Unregister.
func (mr *MockHubMockRecorder) Unregister(conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockHub)(nil).Unregister), conn)
}
