// Code generated by MockGen. DO NOT EDIT.
// Source: logs.go
//
// Generated by this command:
//
//	mockgen -source=logs.go -destination=logs_mock.go -package=logs
//

// Package logs is a generated GoMock package.
package logs

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// AddAllFilters mocks base method.
func (m *MockManager) AddAllFilters(serviceNames []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddAllFilters", serviceNames)
}

// AddAllFilters indicates an expected call of AddAllFilters.
func (mr *MockManagerMockRecorder) AddAllFilters(serviceNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAllFilters", reflect.TypeOf((*MockManager)(nil).AddAllFilters), serviceNames)
}

// AddFilter mocks base method.
func (m *MockManager) AddFilter(serviceName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddFilter", serviceName)
}

// AddFilter indicates an expected call of AddFilter.
func (mr *MockManagerMockRecorder) AddFilter(serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFilter", reflect.TypeOf((*MockManager)(nil).AddFilter), serviceName)
}

// AddLog mocks base method.
func (m *MockManager) AddLog(serviceName, text string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddLog", serviceName, text)
}

// AddLog indicates an expected call of AddLog.
func (mr *MockManagerMockRecorder) AddLog(serviceName, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLog", reflect.TypeOf((*MockManager)(nil).AddLog), serviceName, text)
}

// GetFilterCount mocks base method.
func (m *MockManager) GetFilterCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilterCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetFilterCount indicates an expected call of GetFilterCount.
func (mr *MockManagerMockRecorder) GetFilterCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilterCount", reflect.TypeOf((*MockManager)(nil).GetFilterCount))
}

// GetFilteredLogs mocks base method.
func (m *MockManager) GetFilteredLogs() []Entry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilteredLogs")
	ret0, _ := ret[0].([]Entry)
	return ret0
}

// GetFilteredLogs indicates an expected call of GetFilteredLogs.
func (mr *MockManagerMockRecorder) GetFilteredLogs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilteredLogs", reflect.TypeOf((*MockManager)(nil).GetFilteredLogs))
}

// GetFilteredNames mocks base method.
func (m *MockManager) GetFilteredNames() map[string]bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilteredNames")
	ret0, _ := ret[0].(map[string]bool)
	return ret0
}

// GetFilteredNames indicates an expected call of GetFilteredNames.
func (mr *MockManagerMockRecorder) GetFilteredNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilteredNames", reflect.TypeOf((*MockManager)(nil).GetFilteredNames))
}

// GetLogs mocks base method.
func (m *MockManager) GetLogs() []Entry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogs")
	ret0, _ := ret[0].([]Entry)
	return ret0
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockManagerMockRecorder) GetLogs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockManager)(nil).GetLogs))
}

// IsFiltered mocks base method.
func (m *MockManager) IsFiltered(serviceName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFiltered", serviceName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFiltered indicates an expected call of IsFiltered.
func (mr *MockManagerMockRecorder) IsFiltered(serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFiltered", reflect.TypeOf((*MockManager)(nil).IsFiltered), serviceName)
}

// RemoveFilter mocks base method.
func (m *MockManager) RemoveFilter(serviceName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveFilter", serviceName)
}

// RemoveFilter indicates an expected call of RemoveFilter.
func (mr *MockManagerMockRecorder) RemoveFilter(serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFilter", reflect.TypeOf((*MockManager)(nil).RemoveFilter), serviceName)
}

// ToggleFilter mocks base method.
func (m *MockManager) ToggleFilter(serviceName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ToggleFilter", serviceName)
}

// ToggleFilter indicates an expected call of ToggleFilter.
func (mr *MockManagerMockRecorder) ToggleFilter(serviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleFilter", reflect.TypeOf((*MockManager)(nil).ToggleFilter), serviceName)
}
