// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/logs/screen.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/logs/screen.go -destination=internal/app/logs/screen_mock.go -package=logs
//

// Package logs is a generated GoMock package.
package logs

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockScreen is a mock of Screen interface.
type MockScreen struct {
	ctrl     *gomock.Controller
	recorder *MockScreenMockRecorder
	isgomock struct{}
}

// MockScreenMockRecorder is the mock recorder for MockScreen.
type MockScreenMockRecorder struct {
	mock *MockScreen
}

// NewMockScreen creates a new mock instance.
func NewMockScreen(ctrl *gomock.Controller) *MockScreen {
	mock := &MockScreen{ctrl: ctrl}
	mock.recorder = &MockScreenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScreen) EXPECT() *MockScreenMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockScreen) Run(profile string, services []string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", profile, services)
	ret0, _ := ret[0].(int)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockScreenMockRecorder) Run(profile, services any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockScreen)(nil).Run), profile, services)
}
