// Code generated by MockGen. DO NOT EDIT.
// Source: fuku/internal/app/logs (interfaces: Client,View)
//
// Generated by this command:
//
//	mockgen -destination=internal/app/logs/session_mock_test.go -package=logs fuku/internal/app/logs Client,View
//

// Package logs is a generated GoMock package.
package logs

import (
	context "context"
	contracts "fuku/internal/contracts"
	model "fuku/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// Connect mocks base method.
func (m *MockClient) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockClientMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockClient)(nil).Connect))
}

// Stream mocks base method.
func (m *MockClient) Stream(ctx context.Context, handler Handler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stream", ctx, handler)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stream indicates an expected call of Stream.
func (mr *MockClientMockRecorder) Stream(ctx, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockClient)(nil).Stream), ctx, handler)
}

// Subscribe mocks base method.
func (m *MockClient) Subscribe(services []string, replay model.ReplayOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", services, replay)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockClientMockRecorder) Subscribe(services, replay any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockClient)(nil).Subscribe), services, replay)
}

// MockView is a mock of View interface.
type MockView struct {
	ctrl     *gomock.Controller
	recorder *MockViewMockRecorder
	isgomock struct{}
}

// MockViewMockRecorder is the mock recorder for MockView.
type MockViewMockRecorder struct {
	mock *MockView
}

// NewMockView creates a new mock instance.
func NewMockView(ctrl *gomock.Controller) *MockView {
	mock := &MockView{ctrl: ctrl}
	mock.recorder = &MockViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockView) EXPECT() *MockViewMockRecorder {
	return m.recorder
}

// Line mocks base method.
func (m *MockView) Line(line model.LogLine) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Line", line)
}

// Line indicates an expected call of Line.
func (mr *MockViewMockRecorder) Line(line any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Line", reflect.TypeOf((*MockView)(nil).Line), line)
}

// Status mocks base method.
func (m *MockView) Status(status contracts.LogStatus, subscribed []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Status", status, subscribed)
}

// Status indicates an expected call of Status.
func (mr *MockViewMockRecorder) Status(status, subscribed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockView)(nil).Status), status, subscribed)
}
