// Code generated by MockGen. DO NOT EDIT.
// Source: procstats.go
//
// Generated by this command:
//
//	mockgen -source=procstats.go -destination=procstats_mock.go -package=procstats
//

// Package procstats is a generated GoMock package.
package procstats

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetStats mocks base method.
func (m *MockProvider) GetStats(pid int) Stats {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", pid)
	ret0, _ := ret[0].(Stats)
	return ret0
}

// GetStats indicates an expected call of GetStats.
func (mr *MockProviderMockRecorder) GetStats(pid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockProvider)(nil).GetStats), pid)
}
