// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/api/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/api/handler.go -destination=internal/app/api/handler_mock.go -package=api
//

// Package api is a generated GoMock package.
package api

import (
	relay "fuku/internal/app/relay"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockJournal is a mock of Journal interface.
type MockJournal struct {
	ctrl     *gomock.Controller
	recorder *MockJournalMockRecorder
	isgomock struct{}
}

// MockJournalMockRecorder is the mock recorder for MockJournal.
type MockJournalMockRecorder struct {
	mock *MockJournal
}

// NewMockJournal creates a new mock instance.
func NewMockJournal(ctrl *gomock.Controller) *MockJournal {
	mock := &MockJournal{ctrl: ctrl}
	mock.recorder = &MockJournalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJournal) EXPECT() *MockJournalMockRecorder {
	return m.recorder
}

// History mocks base method.
func (m *MockJournal) History(query relay.HistoryQuery) []relay.LogMessage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History", query)
	ret0, _ := ret[0].([]relay.LogMessage)
	return ret0
}

// History indicates an expected call of History.
func (mr *MockJournalMockRecorder) History(query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockJournal)(nil).History), query)
}
