// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/runner/guard.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/runner/guard.go -destination=internal/app/runner/guard_mock.go -package=runner
//

// Package runner is a generated GoMock package.
package runner

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGuard is a mock of Guard interface.
type MockGuard struct {
	ctrl     *gomock.Controller
	recorder *MockGuardMockRecorder
	isgomock struct{}
}

// MockGuardMockRecorder is the mock recorder for MockGuard.
type MockGuardMockRecorder struct {
	mock *MockGuard
}

// NewMockGuard creates a new mock instance.
func NewMockGuard(ctrl *gomock.Controller) *MockGuard {
	mock := &MockGuard{ctrl: ctrl}
	mock.recorder = &MockGuardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGuard) EXPECT() *MockGuardMockRecorder {
	return m.recorder
}

// IsLocked mocks base method.
func (m *MockGuard) IsLocked(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLocked", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLocked indicates an expected call of IsLocked.
func (mr *MockGuardMockRecorder) IsLocked(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLocked", reflect.TypeOf((*MockGuard)(nil).IsLocked), name)
}

// Lock mocks base method.
func (m *MockGuard) Lock(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Lock indicates an expected call of Lock.
func (mr *MockGuardMockRecorder) Lock(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockGuard)(nil).Lock), name)
}

// Unlock mocks base method.
func (m *MockGuard) Unlock(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unlock", name)
}

// Unlock indicates an expected call of Unlock.
func (mr *MockGuardMockRecorder) Unlock(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockGuard)(nil).Unlock), name)
}
