// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/runner/registry.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/runner/registry.go -destination=internal/app/runner/registry_mock.go -package=runner
//

// Package runner is a generated GoMock package.
package runner

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRegistry is a mock of Registry interface.
type MockRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryMockRecorder
	isgomock struct{}
}

// MockRegistryMockRecorder is the mock recorder for MockRegistry.
type MockRegistryMockRecorder struct {
	mock *MockRegistry
}

// NewMockRegistry creates a new mock instance.
func NewMockRegistry(ctrl *gomock.Controller) *MockRegistry {
	mock := &MockRegistry{ctrl: ctrl}
	mock.recorder = &MockRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistry) EXPECT() *MockRegistryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRegistry) Add(name string, proc Process, tier string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Add", name, proc, tier)
}

// Add indicates an expected call of Add.
func (mr *MockRegistryMockRecorder) Add(name, proc, tier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRegistry)(nil).Add), name, proc, tier)
}

// ClearRestarting mocks base method.
func (m *MockRegistry) ClearRestarting(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearRestarting", name)
}

// ClearRestarting indicates an expected call of ClearRestarting.
func (mr *MockRegistryMockRecorder) ClearRestarting(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearRestarting", reflect.TypeOf((*MockRegistry)(nil).ClearRestarting), name)
}

// Detach mocks base method.
func (m *MockRegistry) Detach(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Detach", name)
}

// Detach indicates an expected call of Detach.
func (mr *MockRegistryMockRecorder) Detach(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detach", reflect.TypeOf((*MockRegistry)(nil).Detach), name)
}

// Get mocks base method.
func (m *MockRegistry) Get(name string) Lookup {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", name)
	ret0, _ := ret[0].(Lookup)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockRegistryMockRecorder) Get(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRegistry)(nil).Get), name)
}

// IsRestarting mocks base method.
func (m *MockRegistry) IsRestarting(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRestarting", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRestarting indicates an expected call of IsRestarting.
func (mr *MockRegistryMockRecorder) IsRestarting(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRestarting", reflect.TypeOf((*MockRegistry)(nil).IsRestarting), name)
}

// MarkRestarting mocks base method.
func (m *MockRegistry) MarkRestarting(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MarkRestarting", name)
}

// MarkRestarting indicates an expected call of MarkRestarting.
func (mr *MockRegistryMockRecorder) MarkRestarting(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRestarting", reflect.TypeOf((*MockRegistry)(nil).MarkRestarting), name)
}

// Remove mocks base method.
func (m *MockRegistry) Remove(name string, proc Process) RemoveResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", name, proc)
	ret0, _ := ret[0].(RemoveResult)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockRegistryMockRecorder) Remove(name, proc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRegistry)(nil).Remove), name, proc)
}

// SnapshotReverse mocks base method.
func (m *MockRegistry) SnapshotReverse() []Process {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotReverse")
	ret0, _ := ret[0].([]Process)
	return ret0
}

// SnapshotReverse indicates an expected call of SnapshotReverse.
func (mr *MockRegistryMockRecorder) SnapshotReverse() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotReverse", reflect.TypeOf((*MockRegistry)(nil).SnapshotReverse))
}

// Wait mocks base method.
func (m *MockRegistry) Wait() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Wait")
}

// Wait indicates an expected call of Wait.
func (mr *MockRegistryMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockRegistry)(nil).Wait))
}
