// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -source=runner.go -destination=runner_mock.go -package=runner
//

// Package runner is a generated GoMock package.
package runner

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRunner is a mock of Runner interface.
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerMockRecorder
	isgomock struct{}
}

// MockRunnerMockRecorder is the mock recorder for MockRunner.
type MockRunnerMockRecorder struct {
	mock *MockRunner
}

// NewMockRunner creates a new mock instance.
func NewMockRunner(ctrl *gomock.Controller) *MockRunner {
	mock := &MockRunner{ctrl: ctrl}
	mock.recorder = &MockRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunner) EXPECT() *MockRunnerMockRecorder {
	return m.recorder
}

// GetControlChannel mocks base method.
func (m *MockRunner) GetControlChannel() chan ServiceControlRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetControlChannel")
	ret0, _ := ret[0].(chan ServiceControlRequest)
	return ret0
}

// GetControlChannel indicates an expected call of GetControlChannel.
func (mr *MockRunnerMockRecorder) GetControlChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetControlChannel", reflect.TypeOf((*MockRunner)(nil).GetControlChannel))
}

// Run mocks base method.
func (m *MockRunner) Run(ctx context.Context, profile string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockRunnerMockRecorder) Run(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRunner)(nil).Run), ctx, profile)
}
