// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/runner/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/runner/service.go -destination=internal/app/runner/service_mock.go -package=runner
//

// Package runner is a generated GoMock package.
package runner

import (
	context "context"
	process "fuku/internal/app/process"
	config "fuku/internal/config"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockService) Start(ctx context.Context, name string, service *config.Service) (process.Process, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, name, service)
	ret0, _ := ret[0].(process.Process)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockServiceMockRecorder) Start(ctx, name, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockService)(nil).Start), ctx, name, service)
}

// Stop mocks base method.
func (m *MockService) Stop(proc process.Process) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", proc)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockServiceMockRecorder) Stop(proc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockService)(nil).Stop), proc)
}
