// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/runner/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/app/runner/service.go -destination=internal/app/runner/service_mock.go -package=runner
//

// Package runner is a generated GoMock package.
package runner

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Restart mocks base method.
func (m *MockService) Restart(ctx context.Context, name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Restart", ctx, name)
}

// Restart indicates an expected call of Restart.
func (mr *MockServiceMockRecorder) Restart(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockService)(nil).Restart), ctx, name)
}

// Start mocks base method.
func (m *MockService) Start(ctx context.Context, name, tier string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, name, tier)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockServiceMockRecorder) Start(ctx, name, tier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockService)(nil).Start), ctx, name, tier)
}

// Stop mocks base method.
func (m *MockService) Stop(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop", name)
}

// Stop indicates an expected call of Stop.
func (mr *MockServiceMockRecorder) Stop(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockService)(nil).Stop), name)
}
